/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0B, Date: 18-Oct-2006.
 */
#ifndef GAML100_H
#define GAML100_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtbersrc/asn1ber.h"
#include "rtsrc/asn1type.h"
#include "rtxmlsrc/asn1xml.h"
#include "libxml/parser.h"

/**
 * Header file for ASN.1 module Gaml100
 */
/**************************************************************/
/*                                                            */
/*  Collectdate                                               */
/*                                                            */
/**************************************************************/

#define TV_Collectdate	(TM_UNIV|TM_PRIM|26)

typedef const char* Collectdate;

EXTERN int asn1E_Collectdate (OSCTXT* pctxt,
   Collectdate pvalue, ASN1TagType tagging);

EXTERN int asn1D_Collectdate (OSCTXT* pctxt, Collectdate *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Collectdate (OSCTXT* pctxt, Collectdate value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Collectdate (OSCTXT* pctxt, Collectdate* pvalue);

/**************************************************************/
/*                                                            */
/*  Group                                                     */
/*                                                            */
/**************************************************************/

#define TV_Group	(TM_UNIV|TM_PRIM|12)

typedef const OSUTF8CHAR* Group;

EXTERN int asn1E_Group (OSCTXT* pctxt,
   Group pvalue, ASN1TagType tagging);

EXTERN int asn1D_Group (OSCTXT* pctxt, Group *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Group (OSCTXT* pctxt, Group value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Group (OSCTXT* pctxt, Group* pvalue);

/**************************************************************/
/*                                                            */
/*  Name                                                      */
/*                                                            */
/**************************************************************/

#define TV_Gaml100_Name	(TM_UNIV|TM_PRIM|12)

typedef const OSUTF8CHAR* Gaml100_Name;

EXTERN int asn1E_Gaml100_Name (OSCTXT* pctxt,
   Gaml100_Name pvalue, ASN1TagType tagging);

EXTERN int asn1D_Gaml100_Name (OSCTXT* pctxt, Gaml100_Name *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Gaml100_Name (OSCTXT* pctxt, Gaml100_Name value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Gaml100_Name (OSCTXT* pctxt, Gaml100_Name* pvalue);

/**************************************************************/
/*                                                            */
/*  Label                                                     */
/*                                                            */
/**************************************************************/

#define TV_Label	(TM_UNIV|TM_PRIM|12)

typedef const OSUTF8CHAR* Label;

EXTERN int asn1E_Label (OSCTXT* pctxt,
   Label pvalue, ASN1TagType tagging);

EXTERN int asn1D_Label (OSCTXT* pctxt, Label *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Label (OSCTXT* pctxt, Label value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Label (OSCTXT* pctxt, Label* pvalue);

/**************************************************************/
/*                                                            */
/*  Linkref                                                   */
/*                                                            */
/**************************************************************/

#define TV_Linkref	(TM_UNIV|TM_PRIM|12)

typedef const OSUTF8CHAR* Linkref;

EXTERN int asn1E_Linkref (OSCTXT* pctxt,
   Linkref pvalue, ASN1TagType tagging);

EXTERN int asn1D_Linkref (OSCTXT* pctxt, Linkref *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Linkref (OSCTXT* pctxt, Linkref value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Linkref (OSCTXT* pctxt, Linkref* pvalue);

/**************************************************************/
/*                                                            */
/*  Units                                                     */
/*                                                            */
/**************************************************************/

#define TV_Units	(TM_UNIV|TM_PRIM|10)

typedef enum {
   Units_aBSORBANCE = 0,
   Units_aMPERES = 1,
   Units_aNGSTROMS = 2,
   Units_aTOMICMASSUNITS = 3,
   Units_cALORIES = 4,
   Units_cELSIUS = 5,
   Units_cENTIMETERS = 6,
   Units_dAYS = 7,
   Units_dECIBELS = 8,
   Units_dEGREES = 9,
   Units_eLECTRONVOLTS = 10,
   Units_eMISSION = 11,
   Units_fAHRENHEIT = 12,
   Units_gHERTZ = 13,
   Units_gRAMS = 14,
   Units_hERTZ = 15,
   Units_hOURS = 16,
   Units_jOULES = 17,
   Units_kELVIN = 18,
   Units_kILOCALORIES = 19,
   Units_kILOGRAMS = 20,
   Units_kILOHERTZ = 21,
   Units_kILOMETERS = 22,
   Units_kILOWATTS = 23,
   Units_kUBELKAMUNK = 24,
   Units_lITERS = 25,
   Units_lOGREFLECTANCE = 26,
   Units_mASSCHARGERATIO = 27,
   Units_mEGAHERTZ = 28,
   Units_mEGAWATTS = 29,
   Units_mETERS = 30,
   Units_mICROGRAMS = 31,
   Units_mICRONS = 32,
   Units_mICROSECONDS = 33,
   Units_mILLIABSORBANCE = 34,
   Units_mILLIAMPS = 35,
   Units_mILLIGRAMS = 36,
   Units_mILLILITERS = 37,
   Units_mILLIMETERS = 38,
   Units_mILLIMOLAR = 39,
   Units_mILLISECONDS = 40,
   Units_mILLIVOLTS = 41,
   Units_mILLIWATTS = 42,
   Units_mINUTES = 43,
   Units_mOLAR = 44,
   Units_mOLES = 45,
   Units_nANOGRAMS = 46,
   Units_nANOMETERS = 47,
   Units_nANOSECONDS = 48,
   Units_pPB = 49,
   Units_pPM = 50,
   Units_pPT = 51,
   Units_rADIANS = 52,
   Units_rAMANSHIFT = 53,
   Units_rEFLECTANCE = 54,
   Units_sECONDS = 55,
   Units_tRANSMISSIONPERCENT = 56,
   Units_tRANSMITTANCE = 57,
   Units_uNKNOWN = 58,
   Units_vOLTS = 59,
   Units_wATTS = 60,
   Units_wAVENUMBER = 61,
   Units_yEARS = 62
} Units_Root;

typedef OSUINT32 Units;

EXTERN int asn1E_Units (OSCTXT* pctxt,
   Units *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Units (OSCTXT* pctxt, Units *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Units (OSCTXT* pctxt, Units value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Units (OSCTXT* pctxt, Units* pvalue);

EXTERN const OSUTF8CHAR* Units_ToString (OSINT32 value);

EXTERN int Units_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Units* pvalue);

/**************************************************************/
/*                                                            */
/*  Linkid                                                    */
/*                                                            */
/**************************************************************/

#define TV_Linkid	(TM_UNIV|TM_PRIM|12)

typedef const OSUTF8CHAR* Linkid;

EXTERN int asn1E_Linkid (OSCTXT* pctxt,
   Linkid pvalue, ASN1TagType tagging);

EXTERN int asn1D_Linkid (OSCTXT* pctxt, Linkid *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Linkid (OSCTXT* pctxt, Linkid value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Linkid (OSCTXT* pctxt, Linkid* pvalue);

/**************************************************************/
/*                                                            */
/*  Valueorder                                                */
/*                                                            */
/**************************************************************/

#define TV_Valueorder	(TM_UNIV|TM_PRIM|10)

typedef enum {
   Valueorder_eVEN = 0,
   Valueorder_oRDERED = 1,
   Valueorder_uNSPECIFIED = 2
} Valueorder_Root;

typedef OSUINT32 Valueorder;

EXTERN int asn1E_Valueorder (OSCTXT* pctxt,
   Valueorder *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Valueorder (OSCTXT* pctxt, Valueorder *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Valueorder (OSCTXT* pctxt, Valueorder value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Valueorder (OSCTXT* pctxt, Valueorder* pvalue);

EXTERN const OSUTF8CHAR* Valueorder_ToString (OSINT32 value);

EXTERN int Valueorder_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Valueorder* pvalue);

/**************************************************************/
/*                                                            */
/*  Technique                                                 */
/*                                                            */
/**************************************************************/

#define TV_Technique	(TM_UNIV|TM_PRIM|10)

typedef enum {
   Technique_aTOMIC = 0,
   Technique_cHROM = 1,
   Technique_fLUOR = 2,
   Technique_iR = 3,
   Technique_mS = 4,
   Technique_nIR = 5,
   Technique_nMR = 6,
   Technique_pARTICLE = 7,
   Technique_pDA = 8,
   Technique_pOLAR = 9,
   Technique_rAMAN = 10,
   Technique_tHERMAL = 11,
   Technique_uNKNOWN = 12,
   Technique_uVVIS = 13,
   Technique_xRAY = 14
} Technique_Root;

typedef OSUINT32 Technique;

EXTERN int asn1E_Technique (OSCTXT* pctxt,
   Technique *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Technique (OSCTXT* pctxt, Technique *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Technique (OSCTXT* pctxt, Technique value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Technique (OSCTXT* pctxt, Technique* pvalue);

EXTERN const OSUTF8CHAR* Technique_ToString (OSINT32 value);

EXTERN int Technique_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Technique* pvalue);

/**************************************************************/
/*                                                            */
/*  GAML_integrity_algorithm                                  */
/*                                                            */
/**************************************************************/

#define TV_GAML_integrity_algorithm	(TM_UNIV|TM_PRIM|10)

typedef enum {
   algorithm_sHA1 = 0
} GAML_integrity_algorithm_Root;

typedef OSUINT32 GAML_integrity_algorithm;

EXTERN int asn1E_GAML_integrity_algorithm (OSCTXT* pctxt,
   GAML_integrity_algorithm *pvalue, ASN1TagType tagging);

EXTERN int asn1D_GAML_integrity_algorithm (OSCTXT* pctxt, 
   GAML_integrity_algorithm *pvalue, ASN1TagType tagging, int length);

EXTERN int XmlEnc_GAML_integrity_algorithm (OSCTXT* pctxt, 
   GAML_integrity_algorithm value, const OSUTF8CHAR* elemName, 
   const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_GAML_integrity_algorithm (OSCTXT* pctxt, 
   GAML_integrity_algorithm* pvalue);

EXTERN const OSUTF8CHAR* GAML_integrity_algorithm_ToString (OSINT32 value);

EXTERN int GAML_integrity_algorithm_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, GAML_integrity_algorithm* pvalue);

/**************************************************************/
/*                                                            */
/*  Values_byteorder                                          */
/*                                                            */
/**************************************************************/

#define TV_Values_byteorder	(TM_UNIV|TM_PRIM|10)

typedef enum {
   byteorder_iNTEL = 0
} Values_byteorder_Root;

typedef OSUINT32 Values_byteorder;

EXTERN int asn1E_Values_byteorder (OSCTXT* pctxt,
   Values_byteorder *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Values_byteorder (OSCTXT* pctxt, Values_byteorder *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Values_byteorder (OSCTXT* pctxt, Values_byteorder value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Values_byteorder (OSCTXT* pctxt, Values_byteorder* pvalue);

EXTERN const OSUTF8CHAR* Values_byteorder_ToString (OSINT32 value);

EXTERN int Values_byteorder_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Values_byteorder* pvalue);

/**************************************************************/
/*                                                            */
/*  Values_format                                             */
/*                                                            */
/**************************************************************/

#define TV_Values_format	(TM_UNIV|TM_PRIM|10)

typedef enum {
   format_fLOAT32 = 0,
   format_fLOAT64 = 1
} Values_format_Root;

typedef OSUINT32 Values_format;

EXTERN int asn1E_Values_format (OSCTXT* pctxt,
   Values_format *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Values_format (OSCTXT* pctxt, Values_format *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Values_format (OSCTXT* pctxt, Values_format value, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Values_format (OSCTXT* pctxt, Values_format* pvalue);

EXTERN const OSUTF8CHAR* Values_format_ToString (OSINT32 value);

EXTERN int Values_format_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Values_format* pvalue);

/**************************************************************/
/*                                                            */
/*  GAML_integrity                                            */
/*                                                            */
/**************************************************************/

#define TV_GAML_integrity	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN GAML_integrity {
   GAML_integrity_algorithm algorithm;
   ASN1DynOctStr base;
} GAML_integrity;

EXTERN int asn1E_GAML_integrity (OSCTXT* pctxt,
   GAML_integrity *pvalue, ASN1TagType tagging);

EXTERN int asn1D_GAML_integrity (OSCTXT* pctxt, GAML_integrity *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_GAML_integrity (OSCTXT* pctxt, GAML_integrity* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_GAML_integrity (OSCTXT* pctxt, GAML_integrity* pvalue);

EXTERN int DOMTest_GAML_integrity (OSCTXT* pctxt, GAML_integrity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_GAML_integrity (GAML_integrity* pvalue);

/**************************************************************/
/*                                                            */
/*  Parameter                                                 */
/*                                                            */
/**************************************************************/

#define TV_Parameter	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Parameter {
   struct {
      unsigned groupPresent : 1;
      unsigned labelPresent : 1;
   } m;
   Group group;
   Label label;
   Gaml100_Name name;
   const OSUTF8CHAR* base;
} Parameter;

EXTERN int asn1E_Parameter (OSCTXT* pctxt,
   Parameter *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Parameter (OSCTXT* pctxt, Parameter *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Parameter (OSCTXT* pctxt, Parameter* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Parameter (OSCTXT* pctxt, Parameter* pvalue);

EXTERN int DOMTest_Parameter (OSCTXT* pctxt, Parameter* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Parameter (Parameter* pvalue);

/**************************************************************/
/*                                                            */
/*  Link                                                      */
/*                                                            */
/**************************************************************/

#define TV_Link	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Link {
   Linkref linkref;
} Link;

EXTERN int asn1E_Link (OSCTXT* pctxt,
   Link *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Link (OSCTXT* pctxt, Link *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Link (OSCTXT* pctxt, Link* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Link (OSCTXT* pctxt, Link* pvalue);

EXTERN int DOMTest_Link (OSCTXT* pctxt, Link* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Link (Link* pvalue);

/**************************************************************/
/*                                                            */
/*  Values                                                    */
/*                                                            */
/**************************************************************/

#define TV_Values	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Values {
   struct {
      unsigned numvaluesPresent : 1;
   } m;
   Values_byteorder byteorder;
   Values_format format;
   OSUINT32 numvalues;
   ASN1DynOctStr base;
} Values;

EXTERN int asn1E_Values (OSCTXT* pctxt,
   Values *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Values (OSCTXT* pctxt, Values *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Values (OSCTXT* pctxt, Values* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Values (OSCTXT* pctxt, Values* pvalue);

EXTERN int DOMTest_Values (OSCTXT* pctxt, Values* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Values (Values* pvalue);

/**************************************************************/
/*                                                            */
/*  Coordinates                                               */
/*                                                            */
/**************************************************************/

#define TV_Coordinates	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Coordinates {
   struct {
      unsigned labelPresent : 1;
      unsigned linkidPresent : 1;
      unsigned valueorderPresent : 1;
   } m;
   Label label;
   Linkid linkid;
   Units units;
   Valueorder valueorder;
   /* List of Link */
   OSRTDList link_list;
   /* List of Parameter */
   OSRTDList parameter_list;
   Values values;
} Coordinates;

EXTERN int asn1E_Coordinates (OSCTXT* pctxt,
   Coordinates *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Coordinates (OSCTXT* pctxt, Coordinates *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Coordinates (OSCTXT* pctxt, Coordinates* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Coordinates (OSCTXT* pctxt, Coordinates* pvalue);

EXTERN int DOMTest_Coordinates (OSCTXT* pctxt, Coordinates* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Coordinates (Coordinates* pvalue);

/**************************************************************/
/*                                                            */
/*  AltXdata                                                  */
/*                                                            */
/**************************************************************/

#define TV_AltXdata	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN AltXdata {
   struct {
      unsigned labelPresent : 1;
      unsigned linkidPresent : 1;
      unsigned valueorderPresent : 1;
   } m;
   Label label;
   Linkid linkid;
   Units units;
   Valueorder valueorder;
   /* List of Link */
   OSRTDList link_list;
   /* List of Parameter */
   OSRTDList parameter_list;
   Values values;
} AltXdata;

EXTERN int asn1E_AltXdata (OSCTXT* pctxt,
   AltXdata *pvalue, ASN1TagType tagging);

EXTERN int asn1D_AltXdata (OSCTXT* pctxt, AltXdata *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_AltXdata (OSCTXT* pctxt, AltXdata* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_AltXdata (OSCTXT* pctxt, AltXdata* pvalue);

EXTERN int DOMTest_AltXdata (OSCTXT* pctxt, AltXdata* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_AltXdata (AltXdata* pvalue);

/**************************************************************/
/*                                                            */
/*  Peaktable_peak_baseline_basecurve_baseXdata               */
/*                                                            */
/**************************************************************/

#define TV_Peaktable_peak_baseline_basecurve_baseXdata	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Peaktable_peak_baseline_basecurve_baseXdata {
   Values values;
} Peaktable_peak_baseline_basecurve_baseXdata;

EXTERN int asn1E_Peaktable_peak_baseline_basecurve_baseXdata (OSCTXT* pctxt,
   Peaktable_peak_baseline_basecurve_baseXdata *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Peaktable_peak_baseline_basecurve_baseXdata (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve_baseXdata *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Peaktable_peak_baseline_basecurve_baseXdata (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve_baseXdata* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Peaktable_peak_baseline_basecurve_baseXdata (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve_baseXdata* pvalue);

EXTERN int DOMTest_Peaktable_peak_baseline_basecurve_baseXdata (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve_baseXdata* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Peaktable_peak_baseline_basecurve_baseXdata (
   Peaktable_peak_baseline_basecurve_baseXdata* pvalue);

/**************************************************************/
/*                                                            */
/*  Peaktable_peak_baseline_basecurve_baseYdata               */
/*                                                            */
/**************************************************************/

#define TV_Peaktable_peak_baseline_basecurve_baseYdata	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Peaktable_peak_baseline_basecurve_baseYdata {
   Values values;
} Peaktable_peak_baseline_basecurve_baseYdata;

EXTERN int asn1E_Peaktable_peak_baseline_basecurve_baseYdata (OSCTXT* pctxt,
   Peaktable_peak_baseline_basecurve_baseYdata *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Peaktable_peak_baseline_basecurve_baseYdata (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve_baseYdata *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Peaktable_peak_baseline_basecurve_baseYdata (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve_baseYdata* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Peaktable_peak_baseline_basecurve_baseYdata (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve_baseYdata* pvalue);

EXTERN int DOMTest_Peaktable_peak_baseline_basecurve_baseYdata (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve_baseYdata* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Peaktable_peak_baseline_basecurve_baseYdata (
   Peaktable_peak_baseline_basecurve_baseYdata* pvalue);

/**************************************************************/
/*                                                            */
/*  Peaktable_peak_baseline_basecurve                         */
/*                                                            */
/**************************************************************/

#define TV_Peaktable_peak_baseline_basecurve	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Peaktable_peak_baseline_basecurve {
   Peaktable_peak_baseline_basecurve_baseXdata baseXdata;
   Peaktable_peak_baseline_basecurve_baseYdata baseYdata;
} Peaktable_peak_baseline_basecurve;

EXTERN int asn1E_Peaktable_peak_baseline_basecurve (OSCTXT* pctxt,
   Peaktable_peak_baseline_basecurve *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Peaktable_peak_baseline_basecurve (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve *pvalue, ASN1TagType tagging, int length);

EXTERN int XmlEnc_Peaktable_peak_baseline_basecurve (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve* pvalue, const OSUTF8CHAR* elemName, 
   const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Peaktable_peak_baseline_basecurve (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve* pvalue);

EXTERN int DOMTest_Peaktable_peak_baseline_basecurve (OSCTXT* pctxt, 
   Peaktable_peak_baseline_basecurve* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Peaktable_peak_baseline_basecurve (
   Peaktable_peak_baseline_basecurve* pvalue);

/**************************************************************/
/*                                                            */
/*  Peaktable_peak_baseline                                   */
/*                                                            */
/**************************************************************/

#define TV_Peaktable_peak_baseline	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Peaktable_peak_baseline {
   struct {
      unsigned basecurvePresent : 1;
   } m;
   /* List of Parameter */
   OSRTDList parameter_list;
   OSREAL startXvalue;
   OSREAL startYvalue;
   OSREAL endXvalue;
   OSREAL endYvalue;
   Peaktable_peak_baseline_basecurve basecurve;
} Peaktable_peak_baseline;

EXTERN int asn1E_Peaktable_peak_baseline (OSCTXT* pctxt,
   Peaktable_peak_baseline *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Peaktable_peak_baseline (OSCTXT* pctxt, 
   Peaktable_peak_baseline *pvalue, ASN1TagType tagging, int length);

EXTERN int XmlEnc_Peaktable_peak_baseline (OSCTXT* pctxt, 
   Peaktable_peak_baseline* pvalue, const OSUTF8CHAR* elemName, 
   const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Peaktable_peak_baseline (OSCTXT* pctxt, 
   Peaktable_peak_baseline* pvalue);

EXTERN int DOMTest_Peaktable_peak_baseline (OSCTXT* pctxt, 
   Peaktable_peak_baseline* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Peaktable_peak_baseline (Peaktable_peak_baseline* pvalue);

/**************************************************************/
/*                                                            */
/*  Peaktable_peak                                            */
/*                                                            */
/**************************************************************/

#define TV_Peaktable_peak	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Peaktable_peak {
   struct {
      unsigned groupPresent : 1;
      unsigned namePresent : 1;
      unsigned baselinePresent : 1;
   } m;
   Group group;
   Gaml100_Name name;
   OSUINT32 number;
   /* List of Parameter */
   OSRTDList parameter_list;
   OSREAL peakXvalue;
   OSREAL peakYvalue;
   Peaktable_peak_baseline baseline;
} Peaktable_peak;

EXTERN int asn1E_Peaktable_peak (OSCTXT* pctxt,
   Peaktable_peak *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Peaktable_peak (OSCTXT* pctxt, Peaktable_peak *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Peaktable_peak (OSCTXT* pctxt, Peaktable_peak* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Peaktable_peak (OSCTXT* pctxt, Peaktable_peak* pvalue);

EXTERN int DOMTest_Peaktable_peak (OSCTXT* pctxt, Peaktable_peak* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Peaktable_peak (Peaktable_peak* pvalue);

/**************************************************************/
/*                                                            */
/*  Peaktable                                                 */
/*                                                            */
/**************************************************************/

#define TV_Peaktable	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Peaktable {
   struct {
      unsigned namePresent : 1;
   } m;
   Gaml100_Name name;
   /* List of Parameter */
   OSRTDList parameter_list;
   /* List of Peaktable_peak */
   OSRTDList peak_list;
} Peaktable;

EXTERN int asn1E_Peaktable (OSCTXT* pctxt,
   Peaktable *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Peaktable (OSCTXT* pctxt, Peaktable *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Peaktable (OSCTXT* pctxt, Peaktable* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Peaktable (OSCTXT* pctxt, Peaktable* pvalue);

EXTERN int DOMTest_Peaktable (OSCTXT* pctxt, Peaktable* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Peaktable (Peaktable* pvalue);

/**************************************************************/
/*                                                            */
/*  Ydata                                                     */
/*                                                            */
/**************************************************************/

#define TV_Ydata	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Ydata {
   struct {
      unsigned labelPresent : 1;
   } m;
   Label label;
   Units units;
   /* List of Parameter */
   OSRTDList parameter_list;
   Values values;
   /* List of Peaktable */
   OSRTDList peaktable_list;
} Ydata;

EXTERN int asn1E_Ydata (OSCTXT* pctxt,
   Ydata *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Ydata (OSCTXT* pctxt, Ydata *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Ydata (OSCTXT* pctxt, Ydata* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Ydata (OSCTXT* pctxt, Ydata* pvalue);

EXTERN int DOMTest_Ydata (OSCTXT* pctxt, Ydata* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Ydata (Ydata* pvalue);

/**************************************************************/
/*                                                            */
/*  Xdata                                                     */
/*                                                            */
/**************************************************************/

#define TV_Xdata	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Xdata {
   struct {
      unsigned labelPresent : 1;
      unsigned linkidPresent : 1;
      unsigned valueorderPresent : 1;
   } m;
   Label label;
   Linkid linkid;
   Units units;
   Valueorder valueorder;
   /* List of Link */
   OSRTDList link_list;
   /* List of Parameter */
   OSRTDList parameter_list;
   Values values;
   /* List of AltXdata */
   OSRTDList altXdata_list;
   /* List of Ydata */
   OSRTDList ydata_list;
} Xdata;

EXTERN int asn1E_Xdata (OSCTXT* pctxt,
   Xdata *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Xdata (OSCTXT* pctxt, Xdata *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Xdata (OSCTXT* pctxt, Xdata* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Xdata (OSCTXT* pctxt, Xdata* pvalue);

EXTERN int DOMTest_Xdata (OSCTXT* pctxt, Xdata* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Xdata (Xdata* pvalue);

/**************************************************************/
/*                                                            */
/*  Trace                                                     */
/*                                                            */
/**************************************************************/

#define TV_Trace	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Trace {
   struct {
      unsigned namePresent : 1;
   } m;
   Gaml100_Name name;
   Technique technique;
   /* List of Parameter */
   OSRTDList parameter_list;
   /* List of Coordinates */
   OSRTDList coordinates_list;
   /* List of Xdata */
   OSRTDList xdata_list;
} Trace;

EXTERN int asn1E_Trace (OSCTXT* pctxt,
   Trace *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Trace (OSCTXT* pctxt, Trace *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Trace (OSCTXT* pctxt, Trace* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Trace (OSCTXT* pctxt, Trace* pvalue);

EXTERN int DOMTest_Trace (OSCTXT* pctxt, Trace* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Trace (Trace* pvalue);

/**************************************************************/
/*                                                            */
/*  Experiment                                                */
/*                                                            */
/**************************************************************/

#define TV_Experiment	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Experiment {
   struct {
      unsigned namePresent : 1;
      unsigned collectdatePresent : 1;
   } m;
   Gaml100_Name name;
   Collectdate collectdate;
   /* List of Parameter */
   OSRTDList parameter_list;
   /* List of Trace */
   OSRTDList trace_list;
} Experiment;

EXTERN int asn1E_Experiment (OSCTXT* pctxt,
   Experiment *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Experiment (OSCTXT* pctxt, Experiment *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Experiment (OSCTXT* pctxt, Experiment* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Experiment (OSCTXT* pctxt, Experiment* pvalue);

EXTERN int DOMTest_Experiment (OSCTXT* pctxt, Experiment* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Experiment (Experiment* pvalue);

/**************************************************************/
/*                                                            */
/*  GAML                                                      */
/*                                                            */
/**************************************************************/

#define TV_GAML	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN GAML {
   struct {
      unsigned namePresent : 1;
      unsigned integrityPresent : 1;
   } m;
   Gaml100_Name name;
   const OSUTF8CHAR* version;
   GAML_integrity integrity;
   /* List of Parameter */
   OSRTDList parameter_list;
   /* List of Experiment */
   OSRTDList experiment_list;
} GAML;

EXTERN int asn1E_GAML (OSCTXT* pctxt,
   GAML *pvalue, ASN1TagType tagging);

EXTERN int asn1D_GAML (OSCTXT* pctxt, GAML *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_GAML (OSCTXT* pctxt, GAML* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_GAML (OSCTXT* pctxt, GAML* pvalue);

EXTERN int DOMTest_GAML (OSCTXT* pctxt, GAML* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_GAML (GAML* pvalue);

/**
 * Global element functions.  These functions encode or decode complete
 * XML documents.  They are generated for XSD global elements and/or
 * ASN.1 type definitions that are either:
 *
 * 1) not referenced by any other types, or
 * 2) explicitly declared to be a PDU using the -pdu command line
 *    option, or
 * 3) explicitly declared to be a PDU using the <isPDU/> 
 *    configuration file element.
 */
EXTERN int XmlEnc_GAML_PDU (OSCTXT* pctxt, GAML* pvalue);

EXTERN int XmlDec_GAML_PDU (OSCTXT* pctxt, GAML* pvalue);

#ifdef __cplusplus
}
#endif

#endif
