/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0B, Date: 18-Oct-2006.
 */
#include "Gaml100.h"
#include "rtxsrc/rtxCommon.h"

/**************************************************************/
/*                                                            */
/*  Collectdate                                               */
/*                                                            */
/**************************************************************/

EXTERN const char* gs_Gaml100_Collectdate_CharSet =
"+-.0123456789:TZ";

/**************************************************************/
/*                                                            */
/*  Group                                                     */
/*                                                            */
/**************************************************************/

/**************************************************************/
/*                                                            */
/*  Name                                                      */
/*                                                            */
/**************************************************************/

/**************************************************************/
/*                                                            */
/*  Label                                                     */
/*                                                            */
/**************************************************************/

/**************************************************************/
/*                                                            */
/*  Linkref                                                   */
/*                                                            */
/**************************************************************/

/**************************************************************/
/*                                                            */
/*  Units                                                     */
/*                                                            */
/**************************************************************/

static const OSEnumItem Units_ENUMTAB[] = {
   { OSUTF8("ABSORBANCE"), 0, 10, 0 },
   { OSUTF8("AMPERES"), 1, 7, 1 },
   { OSUTF8("ANGSTROMS"), 2, 9, 2 },
   { OSUTF8("ATOMICMASSUNITS"), 3, 15, 3 },
   { OSUTF8("CALORIES"), 4, 8, 4 },
   { OSUTF8("CELSIUS"), 5, 7, 5 },
   { OSUTF8("CENTIMETERS"), 6, 11, 6 },
   { OSUTF8("DAYS"), 7, 4, 7 },
   { OSUTF8("DECIBELS"), 8, 8, 8 },
   { OSUTF8("DEGREES"), 9, 7, 9 },
   { OSUTF8("ELECTRONVOLTS"), 10, 13, 10 },
   { OSUTF8("EMISSION"), 11, 8, 11 },
   { OSUTF8("FAHRENHEIT"), 12, 10, 12 },
   { OSUTF8("GHERTZ"), 13, 6, 13 },
   { OSUTF8("GRAMS"), 14, 5, 14 },
   { OSUTF8("HERTZ"), 15, 5, 15 },
   { OSUTF8("HOURS"), 16, 5, 16 },
   { OSUTF8("JOULES"), 17, 6, 17 },
   { OSUTF8("KELVIN"), 18, 6, 18 },
   { OSUTF8("KILOCALORIES"), 19, 12, 19 },
   { OSUTF8("KILOGRAMS"), 20, 9, 20 },
   { OSUTF8("KILOHERTZ"), 21, 9, 21 },
   { OSUTF8("KILOMETERS"), 22, 10, 22 },
   { OSUTF8("KILOWATTS"), 23, 9, 23 },
   { OSUTF8("KUBELKAMUNK"), 24, 11, 24 },
   { OSUTF8("LITERS"), 25, 6, 25 },
   { OSUTF8("LOGREFLECTANCE"), 26, 14, 26 },
   { OSUTF8("MASSCHARGERATIO"), 27, 15, 27 },
   { OSUTF8("MEGAHERTZ"), 28, 9, 28 },
   { OSUTF8("MEGAWATTS"), 29, 9, 29 },
   { OSUTF8("METERS"), 30, 6, 30 },
   { OSUTF8("MICROGRAMS"), 31, 10, 31 },
   { OSUTF8("MICRONS"), 32, 7, 32 },
   { OSUTF8("MICROSECONDS"), 33, 12, 33 },
   { OSUTF8("MILLIABSORBANCE"), 34, 15, 34 },
   { OSUTF8("MILLIAMPS"), 35, 9, 35 },
   { OSUTF8("MILLIGRAMS"), 36, 10, 36 },
   { OSUTF8("MILLILITERS"), 37, 11, 37 },
   { OSUTF8("MILLIMETERS"), 38, 11, 38 },
   { OSUTF8("MILLIMOLAR"), 39, 10, 39 },
   { OSUTF8("MILLISECONDS"), 40, 12, 40 },
   { OSUTF8("MILLIVOLTS"), 41, 10, 41 },
   { OSUTF8("MILLIWATTS"), 42, 10, 42 },
   { OSUTF8("MINUTES"), 43, 7, 43 },
   { OSUTF8("MOLAR"), 44, 5, 44 },
   { OSUTF8("MOLES"), 45, 5, 45 },
   { OSUTF8("NANOGRAMS"), 46, 9, 46 },
   { OSUTF8("NANOMETERS"), 47, 10, 47 },
   { OSUTF8("NANOSECONDS"), 48, 11, 48 },
   { OSUTF8("PPB"), 49, 3, 49 },
   { OSUTF8("PPM"), 50, 3, 50 },
   { OSUTF8("PPT"), 51, 3, 51 },
   { OSUTF8("RADIANS"), 52, 7, 52 },
   { OSUTF8("RAMANSHIFT"), 53, 10, 53 },
   { OSUTF8("REFLECTANCE"), 54, 11, 54 },
   { OSUTF8("SECONDS"), 55, 7, 55 },
   { OSUTF8("TRANSMISSIONPERCENT"), 56, 19, 56 },
   { OSUTF8("TRANSMITTANCE"), 57, 13, 57 },
   { OSUTF8("UNKNOWN"), 58, 7, 58 },
   { OSUTF8("VOLTS"), 59, 5, 59 },
   { OSUTF8("WATTS"), 60, 5, 60 },
   { OSUTF8("WAVENUMBER"), 61, 10, 61 },
   { OSUTF8("YEARS"), 62, 5, 62 }
} ;
#define Units_ENUMTABSIZE 63

const OSUTF8CHAR* Units_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < Units_ENUMTABSIZE) {
      return Units_ENUMTAB[Units_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int Units_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Units* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, Units_ENUMTAB, 
      Units_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (Units)Units_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/**************************************************************/
/*                                                            */
/*  Linkid                                                    */
/*                                                            */
/**************************************************************/

/**************************************************************/
/*                                                            */
/*  Valueorder                                                */
/*                                                            */
/**************************************************************/

static const OSEnumItem Valueorder_ENUMTAB[] = {
   { OSUTF8("EVEN"), 0, 4, 0 },
   { OSUTF8("ORDERED"), 1, 7, 1 },
   { OSUTF8("UNSPECIFIED"), 2, 11, 2 }
} ;
#define Valueorder_ENUMTABSIZE 3

const OSUTF8CHAR* Valueorder_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < Valueorder_ENUMTABSIZE) {
      return Valueorder_ENUMTAB[Valueorder_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int Valueorder_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Valueorder* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, Valueorder_ENUMTAB, 
      Valueorder_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (Valueorder)Valueorder_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/**************************************************************/
/*                                                            */
/*  Technique                                                 */
/*                                                            */
/**************************************************************/

static const OSEnumItem Technique_ENUMTAB[] = {
   { OSUTF8("ATOMIC"), 0, 6, 0 },
   { OSUTF8("CHROM"), 1, 5, 1 },
   { OSUTF8("FLUOR"), 2, 5, 2 },
   { OSUTF8("IR"), 3, 2, 3 },
   { OSUTF8("MS"), 4, 2, 4 },
   { OSUTF8("NIR"), 5, 3, 5 },
   { OSUTF8("NMR"), 6, 3, 6 },
   { OSUTF8("PARTICLE"), 7, 8, 7 },
   { OSUTF8("PDA"), 8, 3, 8 },
   { OSUTF8("POLAR"), 9, 5, 9 },
   { OSUTF8("RAMAN"), 10, 5, 10 },
   { OSUTF8("THERMAL"), 11, 7, 11 },
   { OSUTF8("UNKNOWN"), 12, 7, 12 },
   { OSUTF8("UVVIS"), 13, 5, 13 },
   { OSUTF8("XRAY"), 14, 4, 14 }
} ;
#define Technique_ENUMTABSIZE 15

const OSUTF8CHAR* Technique_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < Technique_ENUMTABSIZE) {
      return Technique_ENUMTAB[Technique_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int Technique_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Technique* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, Technique_ENUMTAB, 
      Technique_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (Technique)Technique_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/**************************************************************/
/*                                                            */
/*  GAML_integrity_algorithm                                  */
/*                                                            */
/**************************************************************/

static const OSEnumItem GAML_integrity_algorithm_ENUMTAB[] = {
   { OSUTF8("SHA1"), 0, 4, 0 }
} ;
#define GAML_integrity_algorithm_ENUMTABSIZE 1

const OSUTF8CHAR* GAML_integrity_algorithm_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < GAML_integrity_algorithm_ENUMTABSIZE) {
      return GAML_integrity_algorithm_ENUMTAB
         [GAML_integrity_algorithm_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int GAML_integrity_algorithm_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, GAML_integrity_algorithm* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      GAML_integrity_algorithm_ENUMTAB, GAML_integrity_algorithm_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (GAML_integrity_algorithm)
         GAML_integrity_algorithm_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/**************************************************************/
/*                                                            */
/*  Values_byteorder                                          */
/*                                                            */
/**************************************************************/

static const OSEnumItem Values_byteorder_ENUMTAB[] = {
   { OSUTF8("INTEL"), 0, 5, 0 }
} ;
#define Values_byteorder_ENUMTABSIZE 1

const OSUTF8CHAR* Values_byteorder_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < Values_byteorder_ENUMTABSIZE) {
      return Values_byteorder_ENUMTAB
         [Values_byteorder_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int Values_byteorder_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Values_byteorder* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, Values_byteorder_ENUMTAB, 
      Values_byteorder_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (Values_byteorder)Values_byteorder_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/**************************************************************/
/*                                                            */
/*  Values_format                                             */
/*                                                            */
/**************************************************************/

static const OSEnumItem Values_format_ENUMTAB[] = {
   { OSUTF8("FLOAT32"), 0, 7, 0 },
   { OSUTF8("FLOAT64"), 1, 7, 1 }
} ;
#define Values_format_ENUMTABSIZE 2

const OSUTF8CHAR* Values_format_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < Values_format_ENUMTABSIZE) {
      return Values_format_ENUMTAB[Values_format_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int Values_format_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Values_format* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, Values_format_ENUMTAB, 
      Values_format_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (Values_format)Values_format_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

/**************************************************************/
/*                                                            */
/*  GAML_integrity                                            */
/*                                                            */
/**************************************************************/

void asn1Init_GAML_integrity (GAML_integrity* pvalue)
{
   if (0 == pvalue) return;
   pvalue->base.numocts = 0;
   pvalue->base.data = 0;
}

/**************************************************************/
/*                                                            */
/*  Parameter                                                 */
/*                                                            */
/**************************************************************/

void asn1Init_Parameter (Parameter* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->group = 0;
   pvalue->label = 0;
   pvalue->name = 0;
   pvalue->base = 0;
}

/**************************************************************/
/*                                                            */
/*  Link                                                      */
/*                                                            */
/**************************************************************/

void asn1Init_Link (Link* pvalue)
{
   if (0 == pvalue) return;
   pvalue->linkref = 0;
}

/**************************************************************/
/*                                                            */
/*  Values                                                    */
/*                                                            */
/**************************************************************/

void asn1Init_Values (Values* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->base.numocts = 0;
   pvalue->base.data = 0;
}

/**************************************************************/
/*                                                            */
/*  Coordinates                                               */
/*                                                            */
/**************************************************************/

void asn1Init_Coordinates (Coordinates* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->label = 0;
   pvalue->linkid = 0;
   rtxDListFastInit (&pvalue->link_list);
   rtxDListFastInit (&pvalue->parameter_list);
   asn1Init_Values (&pvalue->values);
}

/**************************************************************/
/*                                                            */
/*  AltXdata                                                  */
/*                                                            */
/**************************************************************/

void asn1Init_AltXdata (AltXdata* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->label = 0;
   pvalue->linkid = 0;
   rtxDListFastInit (&pvalue->link_list);
   rtxDListFastInit (&pvalue->parameter_list);
   asn1Init_Values (&pvalue->values);
}

/**************************************************************/
/*                                                            */
/*  Peaktable_peak_baseline_basecurve_baseXdata               */
/*                                                            */
/**************************************************************/

void asn1Init_Peaktable_peak_baseline_basecurve_baseXdata (
   Peaktable_peak_baseline_basecurve_baseXdata* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_Values (&pvalue->values);
}

/**************************************************************/
/*                                                            */
/*  Peaktable_peak_baseline_basecurve_baseYdata               */
/*                                                            */
/**************************************************************/

void asn1Init_Peaktable_peak_baseline_basecurve_baseYdata (
   Peaktable_peak_baseline_basecurve_baseYdata* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_Values (&pvalue->values);
}

/**************************************************************/
/*                                                            */
/*  Peaktable_peak_baseline_basecurve                         */
/*                                                            */
/**************************************************************/

void asn1Init_Peaktable_peak_baseline_basecurve (
   Peaktable_peak_baseline_basecurve* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_Peaktable_peak_baseline_basecurve_baseXdata (&pvalue->baseXdata);
   asn1Init_Peaktable_peak_baseline_basecurve_baseYdata (&pvalue->baseYdata);
}

/**************************************************************/
/*                                                            */
/*  Peaktable_peak_baseline                                   */
/*                                                            */
/**************************************************************/

void asn1Init_Peaktable_peak_baseline (Peaktable_peak_baseline* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   rtxDListFastInit (&pvalue->parameter_list);
   asn1Init_Peaktable_peak_baseline_basecurve (&pvalue->basecurve);
}

/**************************************************************/
/*                                                            */
/*  Peaktable_peak                                            */
/*                                                            */
/**************************************************************/

void asn1Init_Peaktable_peak (Peaktable_peak* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->group = 0;
   pvalue->name = 0;
   rtxDListFastInit (&pvalue->parameter_list);
   asn1Init_Peaktable_peak_baseline (&pvalue->baseline);
}

/**************************************************************/
/*                                                            */
/*  Peaktable                                                 */
/*                                                            */
/**************************************************************/

void asn1Init_Peaktable (Peaktable* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->name = 0;
   rtxDListFastInit (&pvalue->parameter_list);
   rtxDListFastInit (&pvalue->peak_list);
}

/**************************************************************/
/*                                                            */
/*  Ydata                                                     */
/*                                                            */
/**************************************************************/

void asn1Init_Ydata (Ydata* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->label = 0;
   rtxDListFastInit (&pvalue->parameter_list);
   asn1Init_Values (&pvalue->values);
   rtxDListFastInit (&pvalue->peaktable_list);
}

/**************************************************************/
/*                                                            */
/*  Xdata                                                     */
/*                                                            */
/**************************************************************/

void asn1Init_Xdata (Xdata* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->label = 0;
   pvalue->linkid = 0;
   rtxDListFastInit (&pvalue->link_list);
   rtxDListFastInit (&pvalue->parameter_list);
   asn1Init_Values (&pvalue->values);
   rtxDListFastInit (&pvalue->altXdata_list);
   rtxDListFastInit (&pvalue->ydata_list);
}

/**************************************************************/
/*                                                            */
/*  Trace                                                     */
/*                                                            */
/**************************************************************/

void asn1Init_Trace (Trace* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->name = 0;
   rtxDListFastInit (&pvalue->parameter_list);
   rtxDListFastInit (&pvalue->coordinates_list);
   rtxDListFastInit (&pvalue->xdata_list);
}

/**************************************************************/
/*                                                            */
/*  Experiment                                                */
/*                                                            */
/**************************************************************/

void asn1Init_Experiment (Experiment* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->name = 0;
   pvalue->collectdate = 0;
   rtxDListFastInit (&pvalue->parameter_list);
   rtxDListFastInit (&pvalue->trace_list);
}

/**************************************************************/
/*                                                            */
/*  GAML                                                      */
/*                                                            */
/**************************************************************/

void asn1Init_GAML (GAML* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   pvalue->name = 0;
   pvalue->version = 0;
   asn1Init_GAML_integrity (&pvalue->integrity);
   rtxDListFastInit (&pvalue->parameter_list);
   rtxDListFastInit (&pvalue->experiment_list);
}

