/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0B, Date: 18-Oct-2006.
 */
#include "Soap-1-1.h"
#include "rtxsrc/rtxCommon.h"

#include "rtxmlsrc/osrtxml.h"

const OSXMLNamespace g_Soap_1_1_NSTable[] = {
   { OSUTF8("tns"), OSUTF8("http://schemas.xmlsoap.org/soap/envelope/") },
   { OSUTF8(""), OSUTF8("") }
} ;

/**************************************************************/
/*                                                            */
/*  MustUnderstand                                            */
/*                                                            */
/**************************************************************/

/**************************************************************/
/*                                                            */
/*  Actor                                                     */
/*                                                            */
/**************************************************************/

/**************************************************************/
/*                                                            */
/*  EncodingStyle_1                                           */
/*                                                            */
/**************************************************************/

void asn1Init_EncodingStyle_1 (EncodingStyle_1* pvalue)
{
   if (0 == pvalue) return;
   rtxDListFastInit (pvalue);
}

/**************************************************************/
/*                                                            */
/*  EncodingStyle                                             */
/*                                                            */
/**************************************************************/

void asn1Init_EncodingStyle (EncodingStyle* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_EncodingStyle_1 (pvalue);
}

/**************************************************************/
/*                                                            */
/*  Header                                                    */
/*                                                            */
/**************************************************************/

void asn1Init_Header (Header* pvalue)
{
   if (0 == pvalue) return;
   rtxDListFastInit (&pvalue->attr);
   rtxDListFastInit (&pvalue->elem_list);
}

/**************************************************************/
/*                                                            */
/*  Body                                                      */
/*                                                            */
/**************************************************************/

void asn1Init_Body (Body* pvalue)
{
   if (0 == pvalue) return;
   rtxDListFastInit (&pvalue->attr);
   rtxDListFastInit (&pvalue->elem_list);
}

/**************************************************************/
/*                                                            */
/*  Envelope                                                  */
/*                                                            */
/**************************************************************/

void asn1Init_Envelope (Envelope* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_EncodingStyle (&pvalue->encodingStyle);
   rtxDListFastInit (&pvalue->attr);
   asn1Init_Header (&pvalue->header);
   asn1Init_Body (&pvalue->body);
   rtxDListFastInit (&pvalue->elem_list);
}

/**************************************************************/
/*                                                            */
/*  Detail                                                    */
/*                                                            */
/**************************************************************/

void asn1Init_Detail (Detail* pvalue)
{
   if (0 == pvalue) return;
   rtxDListFastInit (&pvalue->attr);
   rtxDListFastInit (&pvalue->elem_list);
}

/**************************************************************/
/*                                                            */
/*  Fault                                                     */
/*                                                            */
/**************************************************************/

void asn1Init_Fault (Fault* pvalue)
{
   if (0 == pvalue) return;
   memset (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_XSD_QName (&pvalue->faultcode);
   pvalue->faultstring = 0;
   pvalue->faultactor = 0;
   asn1Init_Detail (&pvalue->detail);
}

