/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0B, Date: 18-Oct-2006.
 */
#ifndef WEBLOG_H
#define WEBLOG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtbersrc/asn1ber.h"
#include "rtsrc/asn1type.h"
#include "rtxmlsrc/asn1xml.h"
#include "libxml/parser.h"

/**
 * Header file for ASN.1 module Weblog
 */
/**************************************************************/
/*                                                            */
/*  Weblog_entry                                              */
/*                                                            */
/**************************************************************/

#define TV_Weblog_entry	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN Weblog_entry {
   const OSUTF8CHAR* host;
   const OSUTF8CHAR* referer;
   const OSUTF8CHAR* userAgent;
   const OSUTF8CHAR* dateTime;
   OSINT16 reqID;
   const OSUTF8CHAR* reqType;
   const OSUTF8CHAR* resource;
   const OSUTF8CHAR* protocol;
   OSUINT16 statusCode;
   const OSUTF8CHAR* byteCount;
} Weblog_entry;

EXTERN int asn1E_Weblog_entry (OSCTXT* pctxt,
   Weblog_entry *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Weblog_entry (OSCTXT* pctxt, Weblog_entry *pvalue, 
   ASN1TagType tagging, int length);

EXTERN int XmlEnc_Weblog_entry (OSCTXT* pctxt, Weblog_entry* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Weblog_entry (OSCTXT* pctxt, Weblog_entry* pvalue);

EXTERN int DOMTest_Weblog_entry (OSCTXT* pctxt, Weblog_entry* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Weblog_entry (Weblog_entry* pvalue);

/**************************************************************/
/*                                                            */
/*  Weblog                                                    */
/*                                                            */
/**************************************************************/

#define TV_Weblog	(TM_UNIV|TM_CONS|16)

/* List of Weblog_entry */
typedef OSRTDList Weblog;

EXTERN int asn1E_Weblog (OSCTXT* pctxt,
   Weblog *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Weblog (OSCTXT* pctxt, Weblog *pvalue, ASN1TagType tagging, 
   int length);

EXTERN int XmlEnc_Weblog (OSCTXT* pctxt, Weblog* pvalue, 
   const OSUTF8CHAR* elemName, const OSUTF8CHAR* nsPrefix);

EXTERN int XmlDec_Weblog (OSCTXT* pctxt, Weblog* pvalue);

EXTERN int DOMTest_Weblog (OSCTXT* pctxt, Weblog* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_Weblog (Weblog* pvalue);

/**
 * Global element functions.  These functions encode or decode complete
 * XML documents.  They are generated for XSD global elements and/or
 * ASN.1 type definitions that are either:
 *
 * 1) not referenced by any other types, or
 * 2) explicitly declared to be a PDU using the -pdu command line
 *    option, or
 * 3) explicitly declared to be a PDU using the <isPDU/> 
 *    configuration file element.
 */
EXTERN int XmlEnc_Weblog_PDU (OSCTXT* pctxt, Weblog* pvalue);

EXTERN int XmlDec_Weblog_PDU (OSCTXT* pctxt, Weblog* pvalue);

#ifdef __cplusplus
}
#endif

#endif
