/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0A, Date: 26-May-2006.
 */
#include "asn1intl.h"
#include "UBL-OrderResponse-1-0.h"
#include "UBL-UnspecializedDatatypes-1-0.h"
#include "UBL-CoreComponentTypes-1-0.h"
#include "UBL-CommonBasicComponents-1-0.h"
#include "UBL-SpecializedDatatypes-1-0.h"
#include "UBL-CodeList-CurrencyCode-1-0.h"
#include "UBL-CodeList-DocumentStatusCode-1-0.h"
#include "UBL-CommonAggregateComponents-1-0.h"
#include "UBL-CodeList-CountryIdentificationCode-1-0.h"
#include "UBL-CodeList-LatitudeDirectionCode-1-0.h"
#include "UBL-CodeList-LongitudeDirectionCode-1-0.h"
#include "UBL-CodeList-ChipCode-1-0.h"
#include "UBL-CodeList-PaymentMeansCode-1-0.h"
#include "UBL-CodeList-AllowanceChargeReasonCode-1-0.h"
#include "UBL-CodeList-ChannelCode-1-0.h"
#include "UBL-CodeList-LineStatusCode-1-0.h"
#include "UBL-CodeList-OperatorCode-1-0.h"
#include "UBL-CodeList-SubstitutionStatusCode-1-0.h"
#include "libxml/parser.h"
#include "rtxmlsrc/osrtxml.h"
#include "rtxsrc/rtxCommon.h"

void asn1DOMTest_UBL_OrderResponse_1_0_EarliestDateType (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_EarliestDateType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_UBL_OrderResponse_1_0_EarliestDate (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_EarliestDate* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_OrderResponse_1_0_EarliestDateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_OrderResponse_1_0_ValidityDurationMeasureType (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_ValidityDurationMeasureType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCodeListVersionID"))) {
            pvalue->m.measureUnitCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCodeListVersionID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_UBL_OrderResponse_1_0_ValidityDurationMeasure (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_ValidityDurationMeasure* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_OrderResponse_1_0_ValidityDurationMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_OrderResponse_1_0_PackagesCountQuantityType (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_PackagesCountQuantityType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListAgencyID"))) {
            pvalue->m.quantityUnitCodeListAgencyIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListAgencyID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListAgencyName"))) {
            pvalue->m.quantityUnitCodeListAgencyNamePresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListAgencyName = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListID"))) {
            pvalue->m.quantityUnitCodeListIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_UBL_OrderResponse_1_0_TotalPackagesCountQuantity (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_TotalPackagesCountQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_OrderResponse_1_0_PackagesCountQuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_OrderResponse_1_0_LineItemCountNumericType (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_LineItemCountNumericType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_UBL_OrderResponse_1_0_LineItemCountNumeric (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_LineItemCountNumeric* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_OrderResponse_1_0_LineItemCountNumericType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_OrderResponseType_orderReference_list (OSCTXT* pctxt, 
   OrderResponseType_orderReference_list* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   OrderReference* pdata = rtxMemAllocTypeZ (pctxt, OrderReference);
   asn1DOMTest_OrderReference (pctxt, pdata, pXmlNode, setChild);
   if (0 != pdata)
      rtxDListAppend (pctxt, pvalue, (void*)pdata);
}

void asn1DOMTest_UBL_OrderResponse_1_0_OriginatorParty (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_OriginatorParty* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PartyType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_OrderResponse_1_0_FreightForwarderParty (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_FreightForwarderParty* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PartyType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_OrderResponse_1_0_DestinationCountry (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_DestinationCountry* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_CountryType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_RespondedOrderLine (OSCTXT* pctxt, 
   RespondedOrderLine* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_OrderLineType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_OrderResponseType_respondedOrderLine_list (OSCTXT* pctxt, 
   OrderResponseType_respondedOrderLine_list* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   RespondedOrderLine* pdata = rtxMemAllocTypeZ (pctxt, RespondedOrderLine);
   asn1DOMTest_RespondedOrderLine (pctxt, pdata, pXmlNode, setChild);
   if (0 != pdata)
      rtxDListAppend (pctxt, pvalue, (void*)pdata);
}

void asn1DOMTest_OrderResponseType (OSCTXT* pctxt, OrderResponseType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   /* Populate elements */
   if (setChild)
      pXmlNode = pXmlNode->children;

   for ( ; 0 != pXmlNode; pXmlNode = pXmlNode->next) {
      if (pXmlNode->type == XML_ELEMENT_NODE) {
         if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("BuyersID"))) {
            pvalue->m.buyersIDPresent = 1;
            asn1DOMTest_UBL_UnspecializedDatatypes_1_0_IdentifierType (pctxt, &pvalue->buyersID, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("SellersID"))) {
            pvalue->m.sellersIDPresent = 1;
            asn1DOMTest_UBL_UnspecializedDatatypes_1_0_IdentifierType (pctxt, &pvalue->sellersID, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("CopyIndicator"))) {
            pvalue->m.copyIndicatorPresent = 1;
            asn1DOMTest_CopyIndicator (pctxt, &pvalue->copyIndicator, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("GUID"))) {
            pvalue->m.gUIDPresent = 1;
            asn1DOMTest_UBL_UnspecializedDatatypes_1_0_IdentifierType (pctxt, &pvalue->gUID, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("IssueDate"))) {
            asn1DOMTest_IssueDate (pctxt, &pvalue->issueDate, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("DocumentStatusCode"))) {
            pvalue->m.documentStatusCodePresent = 1;
            asn1DOMTest_DocumentStatusCodeType (pctxt, &pvalue->documentStatusCode, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("Note"))) {
            pvalue->m.notePresent = 1;
            asn1DOMTest_Note (pctxt, &pvalue->note, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("TransactionCurrencyCode"))) {
            pvalue->m.transactionCurrencyCodePresent = 1;
            asn1DOMTest_CurrencyCodeType (pctxt, &pvalue->transactionCurrencyCode, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("PricingCurrencyCode"))) {
            pvalue->m.pricingCurrencyCodePresent = 1;
            asn1DOMTest_CurrencyCodeType (pctxt, &pvalue->pricingCurrencyCode, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("EarliestDate"))) {
            pvalue->m.earliestDatePresent = 1;
            asn1DOMTest_UBL_OrderResponse_1_0_EarliestDate (pctxt, &pvalue->earliestDate, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("ExpiryDate"))) {
            pvalue->m.expiryDatePresent = 1;
            asn1DOMTest_ExpiryDate (pctxt, &pvalue->expiryDate, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("ValidityDurationMeasure"))) {
            pvalue->m.validityDurationMeasurePresent = 1;
            asn1DOMTest_UBL_OrderResponse_1_0_ValidityDurationMeasure (pctxt, &pvalue->validityDurationMeasure, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("TaxTotalAmount"))) {
            pvalue->m.taxTotalAmountPresent = 1;
            asn1DOMTest_TaxTotalAmount (pctxt, &pvalue->taxTotalAmount, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("LineExtensionTotalAmount"))) {
            pvalue->m.lineExtensionTotalAmountPresent = 1;
            asn1DOMTest_LineExtensionTotalAmount (pctxt, &pvalue->lineExtensionTotalAmount, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("TotalPackagesCountQuantity"))) {
            pvalue->m.totalPackagesCountQuantityPresent = 1;
            asn1DOMTest_UBL_OrderResponse_1_0_TotalPackagesCountQuantity (pctxt, &pvalue->totalPackagesCountQuantity, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("GrossWeightMeasure"))) {
            pvalue->m.grossWeightMeasurePresent = 1;
            asn1DOMTest_GrossWeightMeasure (pctxt, &pvalue->grossWeightMeasure, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("NetWeightMeasure"))) {
            pvalue->m.netWeightMeasurePresent = 1;
            asn1DOMTest_NetWeightMeasure (pctxt, &pvalue->netWeightMeasure, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("NetNetWeightMeasure"))) {
            pvalue->m.netNetWeightMeasurePresent = 1;
            asn1DOMTest_NetNetWeightMeasure (pctxt, &pvalue->netNetWeightMeasure, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("GrossVolumeMeasure"))) {
            pvalue->m.grossVolumeMeasurePresent = 1;
            asn1DOMTest_GrossVolumeMeasure (pctxt, &pvalue->grossVolumeMeasure, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("NetVolumeMeasure"))) {
            pvalue->m.netVolumeMeasurePresent = 1;
            asn1DOMTest_NetVolumeMeasure (pctxt, &pvalue->netVolumeMeasure, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("LineItemCountNumeric"))) {
            pvalue->m.lineItemCountNumericPresent = 1;
            asn1DOMTest_UBL_OrderResponse_1_0_LineItemCountNumeric (pctxt, &pvalue->lineItemCountNumeric, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("OrderReference"))) {
            asn1DOMTest_OrderResponseType_orderReference_list (pctxt, &pvalue->orderReference_list, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("BuyerParty"))) {
            asn1DOMTest_BuyerParty (pctxt, &pvalue->buyerParty, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("SellerParty"))) {
            asn1DOMTest_SellerParty (pctxt, &pvalue->sellerParty, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("OriginatorParty"))) {
            pvalue->m.originatorPartyPresent = 1;
            asn1DOMTest_UBL_OrderResponse_1_0_OriginatorParty (pctxt, &pvalue->originatorParty, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("FreightForwarderParty"))) {
            pvalue->m.freightForwarderPartyPresent = 1;
            asn1DOMTest_UBL_OrderResponse_1_0_FreightForwarderParty (pctxt, &pvalue->freightForwarderParty, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("Delivery"))) {
            asn1DOMTest__SeqOfDelivery (pctxt, &pvalue->delivery_list, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("DeliveryTerms"))) {
            pvalue->m.deliveryTermsPresent = 1;
            asn1DOMTest_DeliveryTerms (pctxt, &pvalue->deliveryTerms, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("AllowanceCharge"))) {
            asn1DOMTest__SeqOfAllowanceCharge (pctxt, &pvalue->allowanceCharge_list, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("SalesConditions"))) {
            pvalue->m.salesConditionsPresent = 1;
            asn1DOMTest_SalesConditions (pctxt, &pvalue->salesConditions, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("DestinationCountry"))) {
            pvalue->m.destinationCountryPresent = 1;
            asn1DOMTest_UBL_OrderResponse_1_0_DestinationCountry (pctxt, &pvalue->destinationCountry, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("RespondedOrderLine"))) {
            asn1DOMTest_OrderResponseType_respondedOrderLine_list (pctxt, &pvalue->respondedOrderLine_list, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("PaymentMeans"))) {
            pvalue->m.paymentMeansPresent = 1;
            asn1DOMTest_PaymentMeans (pctxt, &pvalue->paymentMeans, pXmlNode, TRUE);
         }
      }
   }
}

void asn1DOMTest_OrderResponse (OSCTXT* pctxt, OrderResponse* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_OrderResponseType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_OrderResponse_1_0_PackagesCountQuantity (OSCTXT* pctxt, 
   UBL_OrderResponse_1_0_PackagesCountQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_OrderResponse_1_0_PackagesCountQuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

