/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0A, Date: 26-May-2006.
 */
#include "asn1intl.h"
#include "UBL-CommonBasicComponents-1-0.h"
#include "UBL-SpecializedDatatypes-1-0.h"
#include "UBL-UnspecializedDatatypes-1-0.h"
#include "UBL-CoreComponentTypes-1-0.h"
#include "UBL-CodeList-CurrencyCode-1-0.h"
#include "libxml/parser.h"
#include "rtxmlsrc/osrtxml.h"
#include "rtxsrc/rtxCommon.h"

void asn1DOMTest_DeliveryDateTimeType (OSCTXT* pctxt, 
   DeliveryDateTimeType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_ActualDeliveryDateTime (OSCTXT* pctxt, 
   ActualDeliveryDateTime* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DeliveryDateTimeType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_InformationType (OSCTXT* pctxt, InformationType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_AdditionalInformation (OSCTXT* pctxt, 
   AdditionalInformation* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_InformationType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_StreetNameType (OSCTXT* pctxt, StreetNameType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_AdditionalStreetName (OSCTXT* pctxt, 
   AdditionalStreetName* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_StreetNameType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_AmountType (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_AmountType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyCodeListVersionID"))) {
            pvalue->m.amountCurrencyCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->amountCurrencyCodeListVersionID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyID"))) {
            if (0 != pXmlAttr->children) {
               CurrencyCodeContentType_ToEnum (pXmlAttr->children->content, &pvalue->amountCurrencyID);
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_Amount (OSCTXT* pctxt, Amount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_CommonBasicComponents_1_0_AmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_BackorderQuantity (OSCTXT* pctxt, BackorderQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ReasonType (OSCTXT* pctxt, ReasonType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_BackorderReason (OSCTXT* pctxt, BackorderReason* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ReasonType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_BaseQuantity (OSCTXT* pctxt, BaseQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_BuildingNameType (OSCTXT* pctxt, BuildingNameType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_BuildingName (OSCTXT* pctxt, BuildingName* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_BuildingNameType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_BuildingNumberType (OSCTXT* pctxt, 
   BuildingNumberType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_BuildingNumber (OSCTXT* pctxt, BuildingNumber* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_BuildingNumberType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_CalculationRateType (OSCTXT* pctxt, 
   CalculationRateType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_CalculationRate (OSCTXT* pctxt, CalculationRate* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_CalculationRateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ChargeIndicatorType (OSCTXT* pctxt, 
   ChargeIndicatorType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      OSUTF8CHAR* pcontent = pXmlNode->children->content;
      rtxInitContextBuffer (pctxt, pcontent, rtxUTF8LenBytes(pcontent));
      rtXmlDecBool (pctxt, &pvalue->base);
   }
}

void asn1DOMTest_ChargeIndicator (OSCTXT* pctxt, ChargeIndicator* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ChargeIndicatorType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_CityNameType (OSCTXT* pctxt, CityNameType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_CityName (OSCTXT* pctxt, CityName* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_CityNameType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ConditionType (OSCTXT* pctxt, ConditionType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Condition (OSCTXT* pctxt, Condition* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ConditionType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_CopyIndicatorType (OSCTXT* pctxt, CopyIndicatorType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      OSUTF8CHAR* pcontent = pXmlNode->children->content;
      rtxInitContextBuffer (pctxt, pcontent, rtxUTF8LenBytes(pcontent));
      rtXmlDecBool (pctxt, &pvalue->base);
   }
}

void asn1DOMTest_CopyIndicator (OSCTXT* pctxt, CopyIndicator* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_CopyIndicatorType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_CountrySubentityType (OSCTXT* pctxt, 
   CountrySubentityType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_CountrySubentity (OSCTXT* pctxt, CountrySubentity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_CountrySubentityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_CurrencyBaseRateType (OSCTXT* pctxt, 
   CurrencyBaseRateType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_CurrencyBaseRate (OSCTXT* pctxt, CurrencyBaseRate* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_CurrencyBaseRateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_DeliveredQuantity (OSCTXT* pctxt, DeliveredQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_DeliveryDateTime (OSCTXT* pctxt, DeliveryDateTime* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DeliveryDateTimeType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_DepartmentType (OSCTXT* pctxt, DepartmentType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Department (OSCTXT* pctxt, Department* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DepartmentType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_DescriptionType (OSCTXT* pctxt, DescriptionType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Description (OSCTXT* pctxt, Description* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DescriptionType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_DiscountPercentType (OSCTXT* pctxt, 
   DiscountPercentType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_DiscountPercent (OSCTXT* pctxt, DiscountPercent* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DiscountPercentType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_DistrictType (OSCTXT* pctxt, DistrictType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_District (OSCTXT* pctxt, District* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DistrictType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_PaymentDateType (OSCTXT* pctxt, PaymentDateType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_DuePaymentDate (OSCTXT* pctxt, DuePaymentDate* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PaymentDateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_DurationMeasureType (OSCTXT* pctxt, 
   DurationMeasureType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCodeListVersionID"))) {
            pvalue->m.measureUnitCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCodeListVersionID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_DurationMeasure (OSCTXT* pctxt, DurationMeasure* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DurationMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MailType (OSCTXT* pctxt, MailType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_ElectronicMail (OSCTXT* pctxt, ElectronicMail* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_MailType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_EndDateTimeType (OSCTXT* pctxt, EndDateTimeType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_EndDateTime (OSCTXT* pctxt, EndDateTime* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_EndDateTimeType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ExemptionReason (OSCTXT* pctxt, ExemptionReason* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ReasonType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ExpiryDateType (OSCTXT* pctxt, ExpiryDateType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_ExpiryDate (OSCTXT* pctxt, ExpiryDate* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ExpiryDateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ExtensionType (OSCTXT* pctxt, ExtensionType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Extension (OSCTXT* pctxt, Extension* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ExtensionType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ExtensionAmountType (OSCTXT* pctxt, 
   ExtensionAmountType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyCodeListVersionID"))) {
            pvalue->m.amountCurrencyCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->amountCurrencyCodeListVersionID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyID"))) {
            if (0 != pXmlAttr->children) {
               CurrencyCodeContentType_ToEnum (pXmlAttr->children->content, &pvalue->amountCurrencyID);
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_ExtensionAmount (OSCTXT* pctxt, ExtensionAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ExtensionAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ExtensionTotalAmountType (OSCTXT* pctxt, 
   ExtensionTotalAmountType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyCodeListVersionID"))) {
            pvalue->m.amountCurrencyCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->amountCurrencyCodeListVersionID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyID"))) {
            if (0 != pXmlAttr->children) {
               CurrencyCodeContentType_ToEnum (pXmlAttr->children->content, &pvalue->amountCurrencyID);
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_ExtensionTotalAmount (OSCTXT* pctxt, 
   ExtensionTotalAmount* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ExtensionTotalAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_FloorType (OSCTXT* pctxt, FloorType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Floor (OSCTXT* pctxt, Floor* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_FloorType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_VolumeMeasureType (OSCTXT* pctxt, VolumeMeasureType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCodeListVersionID"))) {
            pvalue->m.measureUnitCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCodeListVersionID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_GrossVolumeMeasure (OSCTXT* pctxt, 
   GrossVolumeMeasure* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_VolumeMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_WeightMeasureType (OSCTXT* pctxt, WeightMeasureType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCodeListVersionID"))) {
            pvalue->m.measureUnitCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCodeListVersionID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_GrossWeightMeasure (OSCTXT* pctxt, 
   GrossWeightMeasure* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_WeightMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_InstructionsType (OSCTXT* pctxt, InstructionsType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_HandlingInstructions (OSCTXT* pctxt, 
   HandlingInstructions* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_InstructionsType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_HolderNameType (OSCTXT* pctxt, HolderNameType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_HolderName (OSCTXT* pctxt, HolderName* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_HolderNameType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_Information (OSCTXT* pctxt, Information* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_InformationType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_InhouseMail (OSCTXT* pctxt, InhouseMail* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_MailType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_Instructions (OSCTXT* pctxt, Instructions* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_InstructionsType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_InvoicedQuantity (OSCTXT* pctxt, InvoicedQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_IssueDateType (OSCTXT* pctxt, IssueDateType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_IssueDate (OSCTXT* pctxt, IssueDate* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_IssueDateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_LatitudeDegreesMeasureType (OSCTXT* pctxt, 
   LatitudeDegreesMeasureType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCodeListVersionID"))) {
            pvalue->m.measureUnitCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCodeListVersionID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_LatitudeDegreesMeasure (OSCTXT* pctxt, 
   LatitudeDegreesMeasure* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_LatitudeDegreesMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_LatitudeMinutesMeasureType (OSCTXT* pctxt, 
   LatitudeMinutesMeasureType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCodeListVersionID"))) {
            pvalue->m.measureUnitCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCodeListVersionID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_LatitudeMinutesMeasure (OSCTXT* pctxt, 
   LatitudeMinutesMeasure* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_LatitudeMinutesMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_LineType (OSCTXT* pctxt, LineType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Line (OSCTXT* pctxt, Line* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_LineType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_LineExtensionAmount (OSCTXT* pctxt, 
   LineExtensionAmount* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ExtensionAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_LineExtensionTotalAmount (OSCTXT* pctxt, 
   LineExtensionTotalAmount* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ExtensionTotalAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_LocationType (OSCTXT* pctxt, LocationType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Location (OSCTXT* pctxt, Location* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_LocationType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_LongitudeDegreesMeasureType (OSCTXT* pctxt, 
   LongitudeDegreesMeasureType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCodeListVersionID"))) {
            pvalue->m.measureUnitCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCodeListVersionID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_LongitudeDegreesMeasure (OSCTXT* pctxt, 
   LongitudeDegreesMeasure* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_LongitudeDegreesMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_LongitudeMinutesMeasureType (OSCTXT* pctxt, 
   LongitudeMinutesMeasureType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCodeListVersionID"))) {
            pvalue->m.measureUnitCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCodeListVersionID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_LongitudeMinutesMeasure (OSCTXT* pctxt, 
   LongitudeMinutesMeasure* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_LongitudeMinutesMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_LossRiskType (OSCTXT* pctxt, LossRiskType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_LossRisk (OSCTXT* pctxt, LossRisk* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_LossRiskType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_Mail (OSCTXT* pctxt, Mail* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_MailType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MarkAttentionIndicatorType (OSCTXT* pctxt, 
   MarkAttentionIndicatorType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      OSUTF8CHAR* pcontent = pXmlNode->children->content;
      rtxInitContextBuffer (pctxt, pcontent, rtxUTF8LenBytes(pcontent));
      rtXmlDecBool (pctxt, &pvalue->base);
   }
}

void asn1DOMTest_MarkAttentionIndicator (OSCTXT* pctxt, 
   MarkAttentionIndicator* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_MarkAttentionIndicatorType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MarkCareIndicatorType (OSCTXT* pctxt, 
   MarkCareIndicatorType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      OSUTF8CHAR* pcontent = pXmlNode->children->content;
      rtxInitContextBuffer (pctxt, pcontent, rtxUTF8LenBytes(pcontent));
      rtXmlDecBool (pctxt, &pvalue->base);
   }
}

void asn1DOMTest_MarkCareIndicator (OSCTXT* pctxt, MarkCareIndicator* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_MarkCareIndicatorType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MaterialIndicatorType (OSCTXT* pctxt, 
   MaterialIndicatorType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      OSUTF8CHAR* pcontent = pXmlNode->children->content;
      rtxInitContextBuffer (pctxt, pcontent, rtxUTF8LenBytes(pcontent));
      rtXmlDecBool (pctxt, &pvalue->base);
   }
}

void asn1DOMTest_MaterialIndicator (OSCTXT* pctxt, MaterialIndicator* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_MaterialIndicatorType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MaximumAmount (OSCTXT* pctxt, MaximumAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_CommonBasicComponents_1_0_AmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_BackorderQuantityType (OSCTXT* pctxt, 
   BackorderQuantityType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListAgencyID"))) {
            pvalue->m.quantityUnitCodeListAgencyIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListAgencyID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListAgencyName"))) {
            pvalue->m.quantityUnitCodeListAgencyNamePresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListAgencyName = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListID"))) {
            pvalue->m.quantityUnitCodeListIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_MaximumBackorderQuantity (OSCTXT* pctxt, 
   MaximumBackorderQuantity* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_BackorderQuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MaximumMeasure (OSCTXT* pctxt, MaximumMeasure* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_MeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MaximumQuantity (OSCTXT* pctxt, MaximumQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_Measure (OSCTXT* pctxt, Measure* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_MeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MinimumAmount (OSCTXT* pctxt, MinimumAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_CommonBasicComponents_1_0_AmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MinimumBackorderQuantity (OSCTXT* pctxt, 
   MinimumBackorderQuantity* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_BackorderQuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MinimumMeasure (OSCTXT* pctxt, MinimumMeasure* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_MeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MinimumQuantity (OSCTXT* pctxt, MinimumQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_MultiplierFactorNumericType (OSCTXT* pctxt, 
   MultiplierFactorNumericType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_MultiplierFactorNumeric (OSCTXT* pctxt, 
   MultiplierFactorNumeric* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_MultiplierFactorNumericType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_Name (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_Name* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_NameType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_NetNetWeightMeasure (OSCTXT* pctxt, 
   NetNetWeightMeasure* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_WeightMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_NetVolumeMeasure (OSCTXT* pctxt, NetVolumeMeasure* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_VolumeMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_NetWeightMeasure (OSCTXT* pctxt, NetWeightMeasure* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_WeightMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_NoteType (OSCTXT* pctxt, NoteType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Note (OSCTXT* pctxt, Note* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_NoteType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_PackQuantityType (OSCTXT* pctxt, PackQuantityType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListAgencyID"))) {
            pvalue->m.quantityUnitCodeListAgencyIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListAgencyID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListAgencyName"))) {
            pvalue->m.quantityUnitCodeListAgencyNamePresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListAgencyName = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListID"))) {
            pvalue->m.quantityUnitCodeListIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_PackQuantity (OSCTXT* pctxt, PackQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PackQuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_PackSizeNumericType (OSCTXT* pctxt, 
   PackSizeNumericType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_PackSizeNumeric (OSCTXT* pctxt, PackSizeNumeric* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PackSizeNumericType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_PaidAmount (OSCTXT* pctxt, PaidAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_CommonBasicComponents_1_0_AmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_PaymentDate (OSCTXT* pctxt, PaymentDate* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PaymentDateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_SurchargePercentType (OSCTXT* pctxt, 
   SurchargePercentType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_PenaltySurchargePercent (OSCTXT* pctxt, 
   PenaltySurchargePercent* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_SurchargePercentType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_PlacardEndorsementType (OSCTXT* pctxt, 
   PlacardEndorsementType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_PlacardEndorsement (OSCTXT* pctxt, 
   PlacardEndorsement* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PlacardEndorsementType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_PlacardNotationType (OSCTXT* pctxt, 
   PlacardNotationType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_PlacardNotation (OSCTXT* pctxt, PlacardNotation* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PlacardNotationType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ZoneType (OSCTXT* pctxt, ZoneType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_PostalZone (OSCTXT* pctxt, PostalZone* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ZoneType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_PostboxType (OSCTXT* pctxt, PostboxType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Postbox (OSCTXT* pctxt, Postbox* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PostboxType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_PriceAmountType (OSCTXT* pctxt, PriceAmountType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyCodeListVersionID"))) {
            pvalue->m.amountCurrencyCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->amountCurrencyCodeListVersionID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyID"))) {
            if (0 != pXmlAttr->children) {
               CurrencyCodeContentType_ToEnum (pXmlAttr->children->content, &pvalue->amountCurrencyID);
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_PriceAmount (OSCTXT* pctxt, PriceAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PriceAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_Quantity (OSCTXT* pctxt, Quantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_Reason (OSCTXT* pctxt, Reason* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ReasonType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ReceivedQuantity (OSCTXT* pctxt, ReceivedQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_RefrigerationOnIndicatorType (OSCTXT* pctxt, 
   RefrigerationOnIndicatorType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      OSUTF8CHAR* pcontent = pXmlNode->children->content;
      rtxInitContextBuffer (pctxt, pcontent, rtxUTF8LenBytes(pcontent));
      rtXmlDecBool (pctxt, &pvalue->base);
   }
}

void asn1DOMTest_RefrigerationOnIndicator (OSCTXT* pctxt, 
   RefrigerationOnIndicator* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_RefrigerationOnIndicatorType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_RegionType (OSCTXT* pctxt, RegionType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Region (OSCTXT* pctxt, Region* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_RegionType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_RegistrationNameType (OSCTXT* pctxt, 
   RegistrationNameType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_RegistrationName (OSCTXT* pctxt, RegistrationName* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_RegistrationNameType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_RejectedQuantity (OSCTXT* pctxt, RejectedQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_RelevantLocation (OSCTXT* pctxt, RelevantLocation* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_LocationType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_RequestedDeliveryDateTime (OSCTXT* pctxt, 
   RequestedDeliveryDateTime* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DeliveryDateTimeType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ReturnableMaterialIndicator (OSCTXT* pctxt, 
   ReturnableMaterialIndicator* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_MaterialIndicatorType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_RoomType (OSCTXT* pctxt, RoomType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Room (OSCTXT* pctxt, Room* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_RoomType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_SequenceNumericType (OSCTXT* pctxt, 
   SequenceNumericType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_SequenceNumeric (OSCTXT* pctxt, SequenceNumeric* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_SequenceNumericType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_SettlementDiscountPercent (OSCTXT* pctxt, 
   SettlementDiscountPercent* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DiscountPercentType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ShortQuantity (OSCTXT* pctxt, ShortQuantity* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_UnspecializedDatatypes_1_0_QuantityType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_SourceCurrencyBaseRate (OSCTXT* pctxt, 
   SourceCurrencyBaseRate* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_CurrencyBaseRateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TermsType (OSCTXT* pctxt, TermsType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_SpecialTerms (OSCTXT* pctxt, SpecialTerms* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TermsType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_StartDateTimeType (OSCTXT* pctxt, StartDateTimeType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_StartDateTime (OSCTXT* pctxt, StartDateTime* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_StartDateTimeType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_StreetName (OSCTXT* pctxt, StreetName* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_StreetNameType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_SurchargePercent (OSCTXT* pctxt, SurchargePercent* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_SurchargePercentType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UnitBaseRateType (OSCTXT* pctxt, UnitBaseRateType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_TargetUnitBaseRate (OSCTXT* pctxt, 
   TargetUnitBaseRate* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UnitBaseRateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TaxableAmount (OSCTXT* pctxt, TaxableAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_CommonBasicComponents_1_0_AmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TaxAmountType (OSCTXT* pctxt, TaxAmountType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyCodeListVersionID"))) {
            pvalue->m.amountCurrencyCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->amountCurrencyCodeListVersionID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyID"))) {
            if (0 != pXmlAttr->children) {
               CurrencyCodeContentType_ToEnum (pXmlAttr->children->content, &pvalue->amountCurrencyID);
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_TaxAmount (OSCTXT* pctxt, TaxAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TaxAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TotalAmountType (OSCTXT* pctxt, TotalAmountType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyCodeListVersionID"))) {
            pvalue->m.amountCurrencyCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->amountCurrencyCodeListVersionID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyID"))) {
            if (0 != pXmlAttr->children) {
               CurrencyCodeContentType_ToEnum (pXmlAttr->children->content, &pvalue->amountCurrencyID);
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_TaxExclusiveTotalAmount (OSCTXT* pctxt, 
   TaxExclusiveTotalAmount* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TotalAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TaxInclusiveTotalAmount (OSCTXT* pctxt, 
   TaxInclusiveTotalAmount* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TotalAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TaxTotalAmountType (OSCTXT* pctxt, 
   TaxTotalAmountType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyCodeListVersionID"))) {
            pvalue->m.amountCurrencyCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->amountCurrencyCodeListVersionID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("amountCurrencyID"))) {
            if (0 != pXmlAttr->children) {
               CurrencyCodeContentType_ToEnum (pXmlAttr->children->content, &pvalue->amountCurrencyID);
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_TaxTotalAmount (OSCTXT* pctxt, TaxTotalAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TaxTotalAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TechnicalName (OSCTXT* pctxt, TechnicalName* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_NameType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TelefaxType (OSCTXT* pctxt, TelefaxType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Telefax (OSCTXT* pctxt, Telefax* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TelefaxType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TelephoneType (OSCTXT* pctxt, TelephoneType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Telephone (OSCTXT* pctxt, Telephone* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TelephoneType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_Terms (OSCTXT* pctxt, Terms* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TermsType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TimezoneOffsetType (OSCTXT* pctxt, 
   TimezoneOffsetType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_TimezoneOffset (OSCTXT* pctxt, TimezoneOffset* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TimezoneOffsetType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TotalAmount (OSCTXT* pctxt, TotalAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TotalAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_TotalTaxAmount (OSCTXT* pctxt, TotalTaxAmount* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TaxAmountType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UnitBaseRate (OSCTXT* pctxt, UnitBaseRate* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UnitBaseRateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_ValidityStartDateType (OSCTXT* pctxt, 
   ValidityStartDateType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_ValidityStartDate (OSCTXT* pctxt, ValidityStartDate* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ValidityStartDateType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_ValueType (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_ValueType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_Value (OSCTXT* pctxt, Value* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_UBL_CommonBasicComponents_1_0_ValueType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_VolumeMeasure (OSCTXT* pctxt, VolumeMeasure* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_VolumeMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_WeightMeasure (OSCTXT* pctxt, WeightMeasure* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_WeightMeasureType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_Zone (OSCTXT* pctxt, Zone* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ZoneType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_DateTimeType (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_DateTimeType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_DateType (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_DateType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_IndicatorType (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_IndicatorType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      OSUTF8CHAR* pcontent = pXmlNode->children->content;
      rtxInitContextBuffer (pctxt, pcontent, rtxUTF8LenBytes(pcontent));
      rtXmlDecBool (pctxt, &pvalue->base);
   }
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_MeasureType (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_MeasureType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("measureUnitCodeListVersionID"))) {
            pvalue->m.measureUnitCodeListVersionIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->measureUnitCodeListVersionID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_NameType (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_NameType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageLocaleID"))) {
            pvalue->m.languageLocaleIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageLocaleID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("languageID"))) {
            pvalue->m.languageIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->languageID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = pXmlNode->children->content;
   }
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_PercentType (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_PercentType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_UBL_CommonBasicComponents_1_0_QuantityType (OSCTXT* pctxt, 
   UBL_CommonBasicComponents_1_0_QuantityType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
         if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCode"))) {
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCode = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListAgencyID"))) {
            pvalue->m.quantityUnitCodeListAgencyIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListAgencyID = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListAgencyName"))) {
            pvalue->m.quantityUnitCodeListAgencyNamePresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListAgencyName = pXmlAttr->children->content;
            }
         }
         else if (rtxUTF8StrEqual (pXmlAttr->name, OSUTF8("quantityUnitCodeListID"))) {
            pvalue->m.quantityUnitCodeListIDPresent = 1;
            if (0 != pXmlAttr->children) {
               pvalue->quantityUnitCodeListID = pXmlAttr->children->content;
            }
         }
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

