/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0A, Date: 26-May-2006.
 */
#ifndef UBL_ORDERCANCELLATION_1_0_H
#define UBL_ORDERCANCELLATION_1_0_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1ber.h"
#include "libxml/parser.h"
#include "UBL-UnspecializedDatatypes-1-0.h"
#include "UBL-CommonBasicComponents-1-0.h"
#include "UBL-CodeList-DocumentStatusCode-1-0.h"
#include "UBL-CommonAggregateComponents-1-0.h"

/**************************************************************/
/*                                                            */
/*  IssueDateTimeType                                         */
/*                                                            */
/**************************************************************/

#define TV_IssueDateTimeType	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN IssueDateTimeType {
   const OSUTF8CHAR* base;
} IssueDateTimeType;

EXTERN int asn1E_IssueDateTimeType (OSCTXT* pctxt,
   IssueDateTimeType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_IssueDateTimeType (OSCTXT* pctxt,
   IssueDateTimeType *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_IssueDateTimeType (OSCTXT* pctxt, IssueDateTimeType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_IssueDateTimeType (IssueDateTimeType* pvalue);

/**************************************************************/
/*                                                            */
/*  IssueDateTime                                             */
/*                                                            */
/**************************************************************/

#define TV_IssueDateTime	(TM_UNIV|TM_CONS|16)

typedef IssueDateTimeType IssueDateTime;

EXTERN int asn1E_IssueDateTime (OSCTXT* pctxt,
   IssueDateTime *pvalue, ASN1TagType tagging);

EXTERN int asn1D_IssueDateTime (OSCTXT* pctxt,
   IssueDateTime *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_IssueDateTime (OSCTXT* pctxt, IssueDateTime* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_IssueDateTime (IssueDateTime* pvalue);

/**************************************************************/
/*                                                            */
/*  CancellationNoteType                                      */
/*                                                            */
/**************************************************************/

#define TV_CancellationNoteType	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN CancellationNoteType {
   struct {
      unsigned languageLocaleIDPresent : 1;
      unsigned languageIDPresent : 1;
   } m;
   const OSUTF8CHAR* languageLocaleID;
   const OSUTF8CHAR* languageID;
   const OSUTF8CHAR* base;
} CancellationNoteType;

EXTERN int asn1E_CancellationNoteType (OSCTXT* pctxt,
   CancellationNoteType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_CancellationNoteType (OSCTXT* pctxt,
   CancellationNoteType *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_CancellationNoteType (OSCTXT* pctxt, 
   CancellationNoteType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_CancellationNoteType (CancellationNoteType* pvalue);

/**************************************************************/
/*                                                            */
/*  CancellationNote                                          */
/*                                                            */
/**************************************************************/

#define TV_CancellationNote	(TM_UNIV|TM_CONS|16)

typedef CancellationNoteType CancellationNote;

EXTERN int asn1E_CancellationNote (OSCTXT* pctxt,
   CancellationNote *pvalue, ASN1TagType tagging);

EXTERN int asn1D_CancellationNote (OSCTXT* pctxt,
   CancellationNote *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_CancellationNote (OSCTXT* pctxt, CancellationNote* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_CancellationNote (CancellationNote* pvalue);

/**************************************************************/
/*                                                            */
/*  ResponseRequiredIndicatorType                             */
/*                                                            */
/**************************************************************/

#define TV_ResponseRequiredIndicatorType	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN ResponseRequiredIndicatorType {
   OSBOOL base;
} ResponseRequiredIndicatorType;

EXTERN int asn1E_ResponseRequiredIndicatorType (OSCTXT* pctxt,
   ResponseRequiredIndicatorType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_ResponseRequiredIndicatorType (OSCTXT* pctxt,
   ResponseRequiredIndicatorType *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_ResponseRequiredIndicatorType (OSCTXT* pctxt, 
   ResponseRequiredIndicatorType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_ResponseRequiredIndicatorType (ResponseRequiredIndicatorType* pvalue);

/**************************************************************/
/*                                                            */
/*  ResponseRequiredIndicator                                 */
/*                                                            */
/**************************************************************/

#define TV_ResponseRequiredIndicator	(TM_UNIV|TM_CONS|16)

typedef ResponseRequiredIndicatorType ResponseRequiredIndicator;

EXTERN int asn1E_ResponseRequiredIndicator (OSCTXT* pctxt,
   ResponseRequiredIndicator *pvalue, ASN1TagType tagging);

EXTERN int asn1D_ResponseRequiredIndicator (OSCTXT* pctxt,
   ResponseRequiredIndicator *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_ResponseRequiredIndicator (OSCTXT* pctxt, 
   ResponseRequiredIndicator* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_ResponseRequiredIndicator (ResponseRequiredIndicator* pvalue);

/**************************************************************/
/*                                                            */
/*  AcceptedIndicatorType                                     */
/*                                                            */
/**************************************************************/

#define TV_AcceptedIndicatorType	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN AcceptedIndicatorType {
   OSBOOL base;
} AcceptedIndicatorType;

EXTERN int asn1E_AcceptedIndicatorType (OSCTXT* pctxt,
   AcceptedIndicatorType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_AcceptedIndicatorType (OSCTXT* pctxt,
   AcceptedIndicatorType *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_AcceptedIndicatorType (OSCTXT* pctxt, 
   AcceptedIndicatorType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_AcceptedIndicatorType (AcceptedIndicatorType* pvalue);

/**************************************************************/
/*                                                            */
/*  AcceptedIndicator                                         */
/*                                                            */
/**************************************************************/

#define TV_AcceptedIndicator	(TM_UNIV|TM_CONS|16)

typedef AcceptedIndicatorType AcceptedIndicator;

EXTERN int asn1E_AcceptedIndicator (OSCTXT* pctxt,
   AcceptedIndicator *pvalue, ASN1TagType tagging);

EXTERN int asn1D_AcceptedIndicator (OSCTXT* pctxt,
   AcceptedIndicator *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_AcceptedIndicator (OSCTXT* pctxt, AcceptedIndicator* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_AcceptedIndicator (AcceptedIndicator* pvalue);

/**************************************************************/
/*                                                            */
/*  OrderCancellationType_orderReference_list                 */
/*                                                            */
/**************************************************************/

#define TV_OrderCancellationType_orderReference_list	(TM_UNIV|TM_CONS|16)

/* List of OrderReference */
typedef OSRTDList OrderCancellationType_orderReference_list;

EXTERN int asn1E_OrderCancellationType_orderReference_list (OSCTXT* pctxt,
   OrderCancellationType_orderReference_list *pvalue, ASN1TagType tagging);

EXTERN int asn1D_OrderCancellationType_orderReference_list (OSCTXT* pctxt,
   OrderCancellationType_orderReference_list *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_OrderCancellationType_orderReference_list (OSCTXT* pctxt, 
   OrderCancellationType_orderReference_list* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_OrderCancellationType_orderReference_list (OrderCancellationType_orderReference_list* pvalue);

/**************************************************************/
/*                                                            */
/*  OrderCancellationType                                     */
/*                                                            */
/**************************************************************/

#define TV_OrderCancellationType	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN OrderCancellationType {
   struct {
      unsigned copyIndicatorPresent : 1;
      unsigned gUIDPresent : 1;
      unsigned documentStatusCodePresent : 1;
      unsigned notePresent : 1;
      unsigned responseRequiredIndicatorPresent : 1;
      unsigned acceptedIndicatorPresent : 1;
   } m;
   UBL_UnspecializedDatatypes_1_0_IdentifierType iD;
   CopyIndicator copyIndicator;
   UBL_UnspecializedDatatypes_1_0_IdentifierType gUID;
   IssueDateTime issueDateTime;
   DocumentStatusCodeType documentStatusCode;
   Note note;
   CancellationNote cancellationNote;
   ResponseRequiredIndicator responseRequiredIndicator;
   AcceptedIndicator acceptedIndicator;
   OrderCancellationType_orderReference_list orderReference_list;
   BuyerParty buyerParty;
   SellerParty sellerParty;
} OrderCancellationType;

EXTERN int asn1E_OrderCancellationType (OSCTXT* pctxt,
   OrderCancellationType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_OrderCancellationType (OSCTXT* pctxt,
   OrderCancellationType *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_OrderCancellationType (OSCTXT* pctxt, 
   OrderCancellationType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_OrderCancellationType (OrderCancellationType* pvalue);

/**************************************************************/
/*                                                            */
/*  OrderCancellation                                         */
/*                                                            */
/**************************************************************/

#define TV_OrderCancellation	(TM_UNIV|TM_CONS|16)

typedef OrderCancellationType OrderCancellation;

EXTERN int asn1E_OrderCancellation (OSCTXT* pctxt,
   OrderCancellation *pvalue, ASN1TagType tagging);

EXTERN int asn1D_OrderCancellation (OSCTXT* pctxt,
   OrderCancellation *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_OrderCancellation (OSCTXT* pctxt, OrderCancellation* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_OrderCancellation (OrderCancellation* pvalue);

#ifdef __cplusplus
}
#endif

#endif
