/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0A, Date: 26-May-2006.
 */
#ifndef UBL_RECEIPTADVICE_1_0_H
#define UBL_RECEIPTADVICE_1_0_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1ber.h"
#include "libxml/parser.h"
#include "UBL-UnspecializedDatatypes-1-0.h"
#include "UBL-CommonBasicComponents-1-0.h"
#include "UBL-CodeList-DocumentStatusCode-1-0.h"
#include "UBL-CommonAggregateComponents-1-0.h"
#include "UBL-DespatchAdvice-1-0.h"

/**************************************************************/
/*                                                            */
/*  DespatchDocumentReference                                 */
/*                                                            */
/**************************************************************/

#define TV_UBL_ReceiptAdvice_1_0_DespatchDocumentReference	(TM_UNIV|TM_CONS|16)

typedef DocumentReferenceType UBL_ReceiptAdvice_1_0_DespatchDocumentReference;

EXTERN int asn1E_UBL_ReceiptAdvice_1_0_DespatchDocumentReference (OSCTXT* pctxt,
   UBL_ReceiptAdvice_1_0_DespatchDocumentReference *pvalue, ASN1TagType tagging);

EXTERN int asn1D_UBL_ReceiptAdvice_1_0_DespatchDocumentReference (OSCTXT* pctxt,
   UBL_ReceiptAdvice_1_0_DespatchDocumentReference *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_UBL_ReceiptAdvice_1_0_DespatchDocumentReference (OSCTXT* pctxt, 
   UBL_ReceiptAdvice_1_0_DespatchDocumentReference* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_UBL_ReceiptAdvice_1_0_DespatchDocumentReference (UBL_ReceiptAdvice_1_0_DespatchDocumentReference* pvalue);

/**************************************************************/
/*                                                            */
/*  _SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference     */
/*                                                            */
/**************************************************************/

#define TV__SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference	(TM_UNIV|TM_CONS|16)

/* List of UBL_ReceiptAdvice_1_0_DespatchDocumentReference */
typedef OSRTDList _SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference;

EXTERN int asn1E__SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference (OSCTXT* pctxt,
   _SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference *pvalue, ASN1TagType tagging);

EXTERN int asn1D__SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference (OSCTXT* pctxt,
   _SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest__SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference (OSCTXT* pctxt, 
   _SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init__SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference (_SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference* pvalue);

/**************************************************************/
/*                                                            */
/*  FreightForwarderParty                                     */
/*                                                            */
/**************************************************************/

#define TV_UBL_ReceiptAdvice_1_0_FreightForwarderParty	(TM_UNIV|TM_CONS|16)

typedef PartyType UBL_ReceiptAdvice_1_0_FreightForwarderParty;

EXTERN int asn1E_UBL_ReceiptAdvice_1_0_FreightForwarderParty (OSCTXT* pctxt,
   UBL_ReceiptAdvice_1_0_FreightForwarderParty *pvalue, ASN1TagType tagging);

EXTERN int asn1D_UBL_ReceiptAdvice_1_0_FreightForwarderParty (OSCTXT* pctxt,
   UBL_ReceiptAdvice_1_0_FreightForwarderParty *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_UBL_ReceiptAdvice_1_0_FreightForwarderParty (OSCTXT* pctxt, 
   UBL_ReceiptAdvice_1_0_FreightForwarderParty* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_UBL_ReceiptAdvice_1_0_FreightForwarderParty (UBL_ReceiptAdvice_1_0_FreightForwarderParty* pvalue);

/**************************************************************/
/*                                                            */
/*  ReceivedTransportHandlingUnit                             */
/*                                                            */
/**************************************************************/

#define TV_ReceivedTransportHandlingUnit	(TM_UNIV|TM_CONS|16)

typedef TransportHandlingUnitType ReceivedTransportHandlingUnit;

EXTERN int asn1E_ReceivedTransportHandlingUnit (OSCTXT* pctxt,
   ReceivedTransportHandlingUnit *pvalue, ASN1TagType tagging);

EXTERN int asn1D_ReceivedTransportHandlingUnit (OSCTXT* pctxt,
   ReceivedTransportHandlingUnit *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_ReceivedTransportHandlingUnit (OSCTXT* pctxt, 
   ReceivedTransportHandlingUnit* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_ReceivedTransportHandlingUnit (ReceivedTransportHandlingUnit* pvalue);

/**************************************************************/
/*                                                            */
/*  _SeqOfReceivedTransportHandlingUnit                       */
/*                                                            */
/**************************************************************/

#define TV__SeqOfReceivedTransportHandlingUnit	(TM_UNIV|TM_CONS|16)

/* List of ReceivedTransportHandlingUnit */
typedef OSRTDList _SeqOfReceivedTransportHandlingUnit;

EXTERN int asn1E__SeqOfReceivedTransportHandlingUnit (OSCTXT* pctxt,
   _SeqOfReceivedTransportHandlingUnit *pvalue, ASN1TagType tagging);

EXTERN int asn1D__SeqOfReceivedTransportHandlingUnit (OSCTXT* pctxt,
   _SeqOfReceivedTransportHandlingUnit *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest__SeqOfReceivedTransportHandlingUnit (OSCTXT* pctxt, 
   _SeqOfReceivedTransportHandlingUnit* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init__SeqOfReceivedTransportHandlingUnit (_SeqOfReceivedTransportHandlingUnit* pvalue);

/**************************************************************/
/*                                                            */
/*  ReceiptAdviceType_receiptLine_list                        */
/*                                                            */
/**************************************************************/

#define TV_ReceiptAdviceType_receiptLine_list	(TM_UNIV|TM_CONS|16)

/* List of ReceiptLine */
typedef OSRTDList ReceiptAdviceType_receiptLine_list;

EXTERN int asn1E_ReceiptAdviceType_receiptLine_list (OSCTXT* pctxt,
   ReceiptAdviceType_receiptLine_list *pvalue, ASN1TagType tagging);

EXTERN int asn1D_ReceiptAdviceType_receiptLine_list (OSCTXT* pctxt,
   ReceiptAdviceType_receiptLine_list *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_ReceiptAdviceType_receiptLine_list (OSCTXT* pctxt, 
   ReceiptAdviceType_receiptLine_list* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_ReceiptAdviceType_receiptLine_list (ReceiptAdviceType_receiptLine_list* pvalue);

/**************************************************************/
/*                                                            */
/*  ReceiptAdviceType                                         */
/*                                                            */
/**************************************************************/

#define TV_ReceiptAdviceType	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN ReceiptAdviceType {
   struct {
      unsigned copyIndicatorPresent : 1;
      unsigned gUIDPresent : 1;
      unsigned documentStatusCodePresent : 1;
      unsigned notePresent : 1;
      unsigned freightForwarderPartyPresent : 1;
   } m;
   UBL_UnspecializedDatatypes_1_0_IdentifierType iD;
   CopyIndicator copyIndicator;
   UBL_UnspecializedDatatypes_1_0_IdentifierType gUID;
   IssueDate issueDate;
   DocumentStatusCodeType documentStatusCode;
   Note note;
   _SeqOfOrderReference orderReference_list;
   _SeqOfUBL_ReceiptAdvice_1_0_DespatchDocumentReference despatchDocumentReference_list;
   BuyerParty buyerParty;
   SellerParty sellerParty;
   UBL_ReceiptAdvice_1_0_FreightForwarderParty freightForwarderParty;
   _SeqOfDelivery delivery_list;
   _SeqOfReceivedTransportHandlingUnit receivedTransportHandlingUnit_list;
   ReceiptAdviceType_receiptLine_list receiptLine_list;
} ReceiptAdviceType;

EXTERN int asn1E_ReceiptAdviceType (OSCTXT* pctxt,
   ReceiptAdviceType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_ReceiptAdviceType (OSCTXT* pctxt,
   ReceiptAdviceType *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_ReceiptAdviceType (OSCTXT* pctxt, ReceiptAdviceType* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_ReceiptAdviceType (ReceiptAdviceType* pvalue);

/**************************************************************/
/*                                                            */
/*  ReceiptAdvice                                             */
/*                                                            */
/**************************************************************/

#define TV_ReceiptAdvice	(TM_UNIV|TM_CONS|16)

typedef ReceiptAdviceType ReceiptAdvice;

EXTERN int asn1E_ReceiptAdvice (OSCTXT* pctxt,
   ReceiptAdvice *pvalue, ASN1TagType tagging);

EXTERN int asn1D_ReceiptAdvice (OSCTXT* pctxt,
   ReceiptAdvice *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_ReceiptAdvice (OSCTXT* pctxt, ReceiptAdvice* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_ReceiptAdvice (ReceiptAdvice* pvalue);

#ifdef __cplusplus
}
#endif

#endif
