/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0A, Date: 26-May-2006.
 */
#ifndef UBL_CODELIST_ALLOWANCECHARGEREASONCODE_1_0_H
#define UBL_CODELIST_ALLOWANCECHARGEREASONCODE_1_0_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1ber.h"
#include "libxml/parser.h"

/**************************************************************/
/*                                                            */
/*  AllowanceChargeReasonCodeContentType                      */
/*                                                            */
/**************************************************************/

#define TV_AllowanceChargeReasonCodeContentType	(TM_UNIV|TM_PRIM|10)

typedef enum {
   zZZ = 0,
   int1 = 1,
   int2 = 2,
   int3 = 3,
   int4 = 4,
   int5 = 5,
   int6 = 6,
   int7 = 7,
   int8 = 8,
   int9 = 9,
   int10 = 10,
   int11 = 11,
   int12 = 12,
   int13 = 13,
   int14 = 14,
   int15 = 15,
   int16 = 16,
   int17 = 17,
   int18 = 18,
   int19 = 19,
   int20 = 20,
   int21 = 21,
   int22 = 22,
   int23 = 23,
   int24 = 24,
   int25 = 25,
   int26 = 26,
   int27 = 27,
   int28 = 28,
   int29 = 29,
   int30 = 30,
   int31 = 31,
   int32 = 32,
   int33 = 33,
   int34 = 34,
   int35 = 35,
   int36 = 36,
   int37 = 37,
   int38 = 38,
   int39 = 39,
   int40 = 40,
   int41 = 41,
   int42 = 42,
   int43 = 43,
   int44 = 44,
   int45 = 45,
   int46 = 46,
   int47 = 47,
   int48 = 48,
   int49 = 49,
   int50 = 50,
   int51 = 51,
   int52 = 52,
   int53 = 53,
   int54 = 54,
   int55 = 55,
   int56 = 56,
   int57 = 57,
   int58 = 58,
   int59 = 59,
   int60 = 60,
   int61 = 61,
   int62 = 62,
   int63 = 63,
   int64 = 64,
   int65 = 65,
   int66 = 66,
   int67 = 67,
   int68 = 68,
   int69 = 69,
   int70 = 70,
   int71 = 71,
   int72 = 72,
   int73 = 73,
   int74 = 74,
   int75 = 75,
   int76 = 76,
   int77 = 77,
   int78 = 78,
   int79 = 79,
   int80 = 80,
   int81 = 81,
   int82 = 82,
   int83 = 83,
   int84 = 84,
   int85 = 85,
   int86 = 86,
   int87 = 87,
   int88 = 88,
   int89 = 89
} AllowanceChargeReasonCodeContentType_Root;

typedef OSUINT32 AllowanceChargeReasonCodeContentType;

EXTERN int asn1E_AllowanceChargeReasonCodeContentType (OSCTXT* pctxt,
   AllowanceChargeReasonCodeContentType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_AllowanceChargeReasonCodeContentType (OSCTXT* pctxt,
   AllowanceChargeReasonCodeContentType *pvalue, ASN1TagType tagging, int length);

EXTERN const OSUTF8CHAR* AllowanceChargeReasonCodeContentType_ToString (OSINT32 value);

EXTERN int AllowanceChargeReasonCodeContentType_ToEnum
  (const OSUTF8CHAR* value, AllowanceChargeReasonCodeContentType* pvalue);

/**************************************************************/
/*                                                            */
/*  AllowanceChargeReasonCodeType                             */
/*                                                            */
/**************************************************************/

#define TV_AllowanceChargeReasonCodeType	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN AllowanceChargeReasonCodeType {
   struct {
      unsigned codeListAgencyIDPresent : 1;
      unsigned codeListAgencyNamePresent : 1;
      unsigned codeListIDPresent : 1;
      unsigned codeListNamePresent : 1;
      unsigned codeListSchemeURIPresent : 1;
      unsigned codeListURIPresent : 1;
      unsigned codeListVersionIDPresent : 1;
      unsigned languageIDPresent : 1;
      unsigned namePresent : 1;
   } m;
   const OSUTF8CHAR* codeListAgencyID;
   const OSUTF8CHAR* codeListAgencyName;
   const OSUTF8CHAR* codeListID;
   const OSUTF8CHAR* codeListName;
   const OSUTF8CHAR* codeListSchemeURI;
   const OSUTF8CHAR* codeListURI;
   const OSUTF8CHAR* codeListVersionID;
   const OSUTF8CHAR* languageID;
   const OSUTF8CHAR* name;
   AllowanceChargeReasonCodeContentType base;
} AllowanceChargeReasonCodeType;

EXTERN int asn1E_AllowanceChargeReasonCodeType (OSCTXT* pctxt,
   AllowanceChargeReasonCodeType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_AllowanceChargeReasonCodeType (OSCTXT* pctxt,
   AllowanceChargeReasonCodeType *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_AllowanceChargeReasonCodeType (OSCTXT* pctxt, 
   AllowanceChargeReasonCodeType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild);

EXTERN void asn1Init_AllowanceChargeReasonCodeType (AllowanceChargeReasonCodeType* pvalue);

#ifdef __cplusplus
}
#endif

#endif
