/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0A, Date: 26-May-2006.
 */
#include "asn1intl.h"
#include "UBL-DespatchAdvice-1-0.h"
#include "UBL-UnspecializedDatatypes-1-0.h"
#include "UBL-CoreComponentTypes-1-0.h"
#include "UBL-CommonBasicComponents-1-0.h"
#include "UBL-SpecializedDatatypes-1-0.h"
#include "UBL-CodeList-CurrencyCode-1-0.h"
#include "UBL-CodeList-DocumentStatusCode-1-0.h"
#include "UBL-CommonAggregateComponents-1-0.h"
#include "UBL-CodeList-CountryIdentificationCode-1-0.h"
#include "UBL-CodeList-LatitudeDirectionCode-1-0.h"
#include "UBL-CodeList-LongitudeDirectionCode-1-0.h"
#include "UBL-CodeList-ChipCode-1-0.h"
#include "UBL-CodeList-PaymentMeansCode-1-0.h"
#include "UBL-CodeList-AllowanceChargeReasonCode-1-0.h"
#include "UBL-CodeList-ChannelCode-1-0.h"
#include "UBL-CodeList-LineStatusCode-1-0.h"
#include "UBL-CodeList-OperatorCode-1-0.h"
#include "UBL-CodeList-SubstitutionStatusCode-1-0.h"
#include "libxml/parser.h"
#include "rtxmlsrc/osrtxml.h"
#include "rtxsrc/rtxCommon.h"

void asn1DOMTest_LineItemCountNumericType (OSCTXT* pctxt, 
   LineItemCountNumericType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   xmlAttrPtr pXmlAttr = pXmlNode->properties;

   /* Populate attributes */
   for ( ; 0 != pXmlAttr; pXmlAttr = pXmlAttr->next) {
      if (pXmlAttr->type == XML_ATTRIBUTE_NODE) {
      }
   }
   /* Populate elements */
   if (0 != pXmlNode->children) {
      pvalue->base = atof (pXmlNode->children->content);
   }
}

void asn1DOMTest_LineItemCountNumeric (OSCTXT* pctxt, 
   LineItemCountNumeric* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_LineItemCountNumericType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest__SeqOfOrderReference (OSCTXT* pctxt, 
   _SeqOfOrderReference* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   OrderReference* pdata = rtxMemAllocTypeZ (pctxt, OrderReference);
   asn1DOMTest_OrderReference (pctxt, pdata, pXmlNode, setChild);
   if (0 != pdata)
      rtxDListAppend (pctxt, pvalue, (void*)pdata);
}

void asn1DOMTest_FreightForwarderParty (OSCTXT* pctxt, 
   FreightForwarderParty* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_PartyType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_DespatchedTransportHandlingUnit (OSCTXT* pctxt, 
   DespatchedTransportHandlingUnit* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_TransportHandlingUnitType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest__SeqOfDespatchedTransportHandlingUnit (OSCTXT* pctxt, 
   _SeqOfDespatchedTransportHandlingUnit* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   DespatchedTransportHandlingUnit* pdata = rtxMemAllocTypeZ (pctxt, DespatchedTransportHandlingUnit);
   asn1DOMTest_DespatchedTransportHandlingUnit (pctxt, pdata, pXmlNode, setChild);
   if (0 != pdata)
      rtxDListAppend (pctxt, pvalue, (void*)pdata);
}

void asn1DOMTest_ActualShipment (OSCTXT* pctxt, ActualShipment* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_ShipmentType (pctxt, pvalue, pXmlNode, TRUE);
}

void asn1DOMTest_DespatchAdviceType_despatchLine_list (OSCTXT* pctxt, 
   DespatchAdviceType_despatchLine_list* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   DespatchLine* pdata = rtxMemAllocTypeZ (pctxt, DespatchLine);
   asn1DOMTest_DespatchLine (pctxt, pdata, pXmlNode, setChild);
   if (0 != pdata)
      rtxDListAppend (pctxt, pvalue, (void*)pdata);
}

void asn1DOMTest_DespatchAdviceType (OSCTXT* pctxt, 
   DespatchAdviceType* pvalue, xmlNodePtr pXmlNode, OSBOOL setChild)
{
   /* Populate elements */
   if (setChild)
      pXmlNode = pXmlNode->children;

   for ( ; 0 != pXmlNode; pXmlNode = pXmlNode->next) {
      if (pXmlNode->type == XML_ELEMENT_NODE) {
         if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("ID"))) {
            asn1DOMTest_UBL_UnspecializedDatatypes_1_0_IdentifierType (pctxt, &pvalue->iD, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("CopyIndicator"))) {
            pvalue->m.copyIndicatorPresent = 1;
            asn1DOMTest_CopyIndicator (pctxt, &pvalue->copyIndicator, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("GUID"))) {
            pvalue->m.gUIDPresent = 1;
            asn1DOMTest_UBL_UnspecializedDatatypes_1_0_IdentifierType (pctxt, &pvalue->gUID, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("IssueDate"))) {
            asn1DOMTest_IssueDate (pctxt, &pvalue->issueDate, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("DocumentStatusCode"))) {
            pvalue->m.documentStatusCodePresent = 1;
            asn1DOMTest_DocumentStatusCodeType (pctxt, &pvalue->documentStatusCode, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("DespatchAdviceTypeCode"))) {
            pvalue->m.despatchAdviceTypeCodePresent = 1;
            asn1DOMTest_UBL_UnspecializedDatatypes_1_0_CodeType (pctxt, &pvalue->despatchAdviceTypeCode, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("Note"))) {
            pvalue->m.notePresent = 1;
            asn1DOMTest_Note (pctxt, &pvalue->note, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("LineItemCountNumeric"))) {
            pvalue->m.lineItemCountNumericPresent = 1;
            asn1DOMTest_LineItemCountNumeric (pctxt, &pvalue->lineItemCountNumeric, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("OrderReference"))) {
            asn1DOMTest__SeqOfOrderReference (pctxt, &pvalue->orderReference_list, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("BuyerParty"))) {
            asn1DOMTest_BuyerParty (pctxt, &pvalue->buyerParty, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("SellerParty"))) {
            asn1DOMTest_SellerParty (pctxt, &pvalue->sellerParty, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("FreightForwarderParty"))) {
            pvalue->m.freightForwarderPartyPresent = 1;
            asn1DOMTest_FreightForwarderParty (pctxt, &pvalue->freightForwarderParty, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("Delivery"))) {
            asn1DOMTest__SeqOfDelivery (pctxt, &pvalue->delivery_list, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("DeliveryTerms"))) {
            pvalue->m.deliveryTermsPresent = 1;
            asn1DOMTest_DeliveryTerms (pctxt, &pvalue->deliveryTerms, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("DespatchedTransportHandlingUnit"))) {
            asn1DOMTest__SeqOfDespatchedTransportHandlingUnit (pctxt, &pvalue->despatchedTransportHandlingUnit_list, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("ActualShipment"))) {
            pvalue->m.actualShipmentPresent = 1;
            asn1DOMTest_ActualShipment (pctxt, &pvalue->actualShipment, pXmlNode, TRUE);
         }
         else if (rtxUTF8StrEqual (pXmlNode->name, OSUTF8("DespatchLine"))) {
            asn1DOMTest_DespatchAdviceType_despatchLine_list (pctxt, &pvalue->despatchLine_list, pXmlNode, TRUE);
         }
      }
   }
}

void asn1DOMTest_DespatchAdvice (OSCTXT* pctxt, DespatchAdvice* pvalue, 
   xmlNodePtr pXmlNode, OSBOOL setChild)
{
   asn1DOMTest_DespatchAdviceType (pctxt, pvalue, pXmlNode, TRUE);
}

