/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.0A, Date: 21-Feb-2006.
 */
#ifndef XSD_H
#define XSD_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1ber.h"
#include "libxml/parser.h"

/**************************************************************/
/*                                                            */
/*  XMLCompatibleString                                       */
/*                                                            */
/**************************************************************/

typedef ASN1UTF8String XMLCompatibleString;

EXTERN int asn1E_XMLCompatibleString (OSCTXT* pctxt,
   XMLCompatibleString *pvalue, ASN1TagType tagging);

EXTERN int asn1D_XMLCompatibleString (OSCTXT* pctxt,
   XMLCompatibleString *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  String                                                    */
/*                                                            */
/**************************************************************/

typedef XMLCompatibleString String;

EXTERN int asn1E_String (OSCTXT* pctxt,
   String *pvalue, ASN1TagType tagging);

EXTERN int asn1D_String (OSCTXT* pctxt,
   String *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  NormalizedString                                          */
/*                                                            */
/**************************************************************/

typedef String NormalizedString;

EXTERN int asn1E_NormalizedString (OSCTXT* pctxt,
   NormalizedString *pvalue, ASN1TagType tagging);

EXTERN int asn1D_NormalizedString (OSCTXT* pctxt,
   NormalizedString *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  XMLStringWithNoCRLFHT                                     */
/*                                                            */
/**************************************************************/

typedef ASN1UTF8String XMLStringWithNoCRLFHT;

EXTERN int asn1E_XMLStringWithNoCRLFHT (OSCTXT* pctxt,
   XMLStringWithNoCRLFHT *pvalue, ASN1TagType tagging);

EXTERN int asn1D_XMLStringWithNoCRLFHT (OSCTXT* pctxt,
   XMLStringWithNoCRLFHT *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  AnyURI                                                    */
/*                                                            */
/**************************************************************/

typedef XMLStringWithNoCRLFHT AnyURI;

EXTERN int asn1E_AnyURI (OSCTXT* pctxt,
   AnyURI *pvalue, ASN1TagType tagging);

EXTERN int asn1D_AnyURI (OSCTXT* pctxt,
   AnyURI *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Language                                                  */
/*                                                            */
/**************************************************************/

typedef ASN1VisibleString XSD_Language;

EXTERN int asn1E_XSD_Language (OSCTXT* pctxt,
   XSD_Language *pvalue, ASN1TagType tagging);

EXTERN int asn1D_XSD_Language (OSCTXT* pctxt,
   XSD_Language *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  DATE_TIME                                                 */
/*                                                            */
/**************************************************************/

typedef ASN1VisibleString DATE_TIME;

EXTERN int asn1E_DATE_TIME (OSCTXT* pctxt,
   DATE_TIME *pvalue, ASN1TagType tagging);

EXTERN int asn1D_DATE_TIME (OSCTXT* pctxt,
   DATE_TIME *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  DateTime                                                  */
/*                                                            */
/**************************************************************/

typedef DATE_TIME XSD_DateTime;

EXTERN int asn1E_XSD_DateTime (OSCTXT* pctxt,
   XSD_DateTime *pvalue, ASN1TagType tagging);

EXTERN int asn1D_XSD_DateTime (OSCTXT* pctxt,
   XSD_DateTime *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Date                                                      */
/*                                                            */
/**************************************************************/

typedef DATE_TIME XSD_Date;

EXTERN int asn1E_XSD_Date (OSCTXT* pctxt,
   XSD_Date *pvalue, ASN1TagType tagging);

EXTERN int asn1D_XSD_Date (OSCTXT* pctxt,
   XSD_Date *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Time                                                      */
/*                                                            */
/**************************************************************/

typedef DATE_TIME Time;

EXTERN int asn1E_Time (OSCTXT* pctxt,
   Time *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Time (OSCTXT* pctxt,
   Time *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  AnySimpleType                                             */
/*                                                            */
/**************************************************************/

typedef XMLCompatibleString AnySimpleType;

EXTERN int asn1E_AnySimpleType (OSCTXT* pctxt,
   AnySimpleType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_AnySimpleType (OSCTXT* pctxt,
   AnySimpleType *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Base64Binary                                              */
/*                                                            */
/**************************************************************/

typedef ASN1DynOctStr Base64Binary;

EXTERN int asn1E_Base64Binary (OSCTXT* pctxt,
   Base64Binary *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Base64Binary (OSCTXT* pctxt,
   Base64Binary *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Boolean                                                   */
/*                                                            */
/**************************************************************/

typedef OSBOOL Boolean;

EXTERN int asn1E_Boolean (OSCTXT* pctxt,
   Boolean *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Boolean (OSCTXT* pctxt,
   Boolean *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Byte                                                      */
/*                                                            */
/**************************************************************/

typedef OSINT8 Byte;

EXTERN int asn1E_Byte (OSCTXT* pctxt,
   Byte *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Byte (OSCTXT* pctxt,
   Byte *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Decimal                                                   */
/*                                                            */
/**************************************************************/

typedef OSREAL Decimal;

EXTERN int asn1E_Decimal (OSCTXT* pctxt,
   Decimal *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Decimal (OSCTXT* pctxt,
   Decimal *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Double                                                    */
/*                                                            */
/**************************************************************/

typedef OSREAL Double;

EXTERN int asn1E_Double (OSCTXT* pctxt,
   Double *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Double (OSCTXT* pctxt,
   Double *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  DURATION                                                  */
/*                                                            */
/**************************************************************/

typedef ASN1VisibleString DURATION;

EXTERN int asn1E_DURATION (OSCTXT* pctxt,
   DURATION *pvalue, ASN1TagType tagging);

EXTERN int asn1D_DURATION (OSCTXT* pctxt,
   DURATION *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Duration                                                  */
/*                                                            */
/**************************************************************/

typedef DURATION Duration;

EXTERN int asn1E_Duration (OSCTXT* pctxt,
   Duration *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Duration (OSCTXT* pctxt,
   Duration *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Token                                                     */
/*                                                            */
/**************************************************************/

typedef NormalizedString Token;

EXTERN int asn1E_Token (OSCTXT* pctxt,
   Token *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Token (OSCTXT* pctxt,
   Token *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Name                                                      */
/*                                                            */
/**************************************************************/

typedef Token XSD_Name;

EXTERN int asn1E_XSD_Name (OSCTXT* pctxt,
   XSD_Name *pvalue, ASN1TagType tagging);

EXTERN int asn1D_XSD_Name (OSCTXT* pctxt,
   XSD_Name *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  NCName                                                    */
/*                                                            */
/**************************************************************/

typedef XSD_Name NCName;

EXTERN int asn1E_NCName (OSCTXT* pctxt,
   NCName *pvalue, ASN1TagType tagging);

EXTERN int asn1D_NCName (OSCTXT* pctxt,
   NCName *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  ENTITY                                                    */
/*                                                            */
/**************************************************************/

typedef NCName ENTITY;

EXTERN int asn1E_ENTITY (OSCTXT* pctxt,
   ENTITY *pvalue, ASN1TagType tagging);

EXTERN int asn1D_ENTITY (OSCTXT* pctxt,
   ENTITY *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Float                                                     */
/*                                                            */
/**************************************************************/

typedef OSREAL Float;

EXTERN int asn1E_Float (OSCTXT* pctxt,
   Float *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Float (OSCTXT* pctxt,
   Float *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  GDay                                                      */
/*                                                            */
/**************************************************************/

typedef DATE_TIME GDay;

EXTERN int asn1E_GDay (OSCTXT* pctxt,
   GDay *pvalue, ASN1TagType tagging);

EXTERN int asn1D_GDay (OSCTXT* pctxt,
   GDay *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  GMonth                                                    */
/*                                                            */
/**************************************************************/

typedef DATE_TIME GMonth;

EXTERN int asn1E_GMonth (OSCTXT* pctxt,
   GMonth *pvalue, ASN1TagType tagging);

EXTERN int asn1D_GMonth (OSCTXT* pctxt,
   GMonth *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  GMonthDay                                                 */
/*                                                            */
/**************************************************************/

typedef DATE_TIME GMonthDay;

EXTERN int asn1E_GMonthDay (OSCTXT* pctxt,
   GMonthDay *pvalue, ASN1TagType tagging);

EXTERN int asn1D_GMonthDay (OSCTXT* pctxt,
   GMonthDay *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  GYear                                                     */
/*                                                            */
/**************************************************************/

typedef DATE_TIME GYear;

EXTERN int asn1E_GYear (OSCTXT* pctxt,
   GYear *pvalue, ASN1TagType tagging);

EXTERN int asn1D_GYear (OSCTXT* pctxt,
   GYear *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  GYearMonth                                                */
/*                                                            */
/**************************************************************/

typedef DATE_TIME GYearMonth;

EXTERN int asn1E_GYearMonth (OSCTXT* pctxt,
   GYearMonth *pvalue, ASN1TagType tagging);

EXTERN int asn1D_GYearMonth (OSCTXT* pctxt,
   GYearMonth *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  HexBinary                                                 */
/*                                                            */
/**************************************************************/

typedef ASN1DynOctStr HexBinary;

EXTERN int asn1E_HexBinary (OSCTXT* pctxt,
   HexBinary *pvalue, ASN1TagType tagging);

EXTERN int asn1D_HexBinary (OSCTXT* pctxt,
   HexBinary *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  ID                                                        */
/*                                                            */
/**************************************************************/

typedef NCName ID;

EXTERN int asn1E_ID (OSCTXT* pctxt,
   ID *pvalue, ASN1TagType tagging);

EXTERN int asn1D_ID (OSCTXT* pctxt,
   ID *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  IDREF                                                     */
/*                                                            */
/**************************************************************/

typedef NCName IDREF;

EXTERN int asn1E_IDREF (OSCTXT* pctxt,
   IDREF *pvalue, ASN1TagType tagging);

EXTERN int asn1D_IDREF (OSCTXT* pctxt,
   IDREF *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Int                                                       */
/*                                                            */
/**************************************************************/

typedef OSINT32 Int;

EXTERN int asn1E_Int (OSCTXT* pctxt,
   Int *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Int (OSCTXT* pctxt,
   Int *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Integer                                                   */
/*                                                            */
/**************************************************************/

typedef OSINT32 Integer;

EXTERN int asn1E_Integer (OSCTXT* pctxt,
   Integer *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Integer (OSCTXT* pctxt,
   Integer *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Long                                                      */
/*                                                            */
/**************************************************************/

typedef OSINT64 Long;

EXTERN int asn1E_Long (OSCTXT* pctxt,
   Long *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Long (OSCTXT* pctxt,
   Long *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  NegativeInteger                                           */
/*                                                            */
/**************************************************************/

typedef OSINT32 NegativeInteger;

EXTERN int asn1E_NegativeInteger (OSCTXT* pctxt,
   NegativeInteger *pvalue, ASN1TagType tagging);

EXTERN int asn1D_NegativeInteger (OSCTXT* pctxt,
   NegativeInteger *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  NMTOKEN                                                   */
/*                                                            */
/**************************************************************/

typedef Token NMTOKEN;

EXTERN int asn1E_NMTOKEN (OSCTXT* pctxt,
   NMTOKEN *pvalue, ASN1TagType tagging);

EXTERN int asn1D_NMTOKEN (OSCTXT* pctxt,
   NMTOKEN *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  NonNegativeInteger                                        */
/*                                                            */
/**************************************************************/

typedef OSUINT32 NonNegativeInteger;

EXTERN int asn1E_NonNegativeInteger (OSCTXT* pctxt,
   NonNegativeInteger *pvalue, ASN1TagType tagging);

EXTERN int asn1D_NonNegativeInteger (OSCTXT* pctxt,
   NonNegativeInteger *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  NonPositiveInteger                                        */
/*                                                            */
/**************************************************************/

typedef OSINT32 NonPositiveInteger;

EXTERN int asn1E_NonPositiveInteger (OSCTXT* pctxt,
   NonPositiveInteger *pvalue, ASN1TagType tagging);

EXTERN int asn1D_NonPositiveInteger (OSCTXT* pctxt,
   NonPositiveInteger *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  QName                                                     */
/*                                                            */
/**************************************************************/

typedef struct EXTERN QName {
   struct {
      unsigned uriPresent : 1;
   } m;
   AnyURI uri;
   NCName name;
} QName;

EXTERN int asn1E_QName (OSCTXT* pctxt,
   QName *pvalue, ASN1TagType tagging);

EXTERN int asn1D_QName (OSCTXT* pctxt,
   QName *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_QName (OSCTXT* pctxt, QName* pvalue, xmlNodePtr pXmlNode);

/**************************************************************/
/*                                                            */
/*  NOTATION                                                  */
/*                                                            */
/**************************************************************/

typedef QName NOTATION;

EXTERN int asn1E_NOTATION (OSCTXT* pctxt,
   NOTATION *pvalue, ASN1TagType tagging);

EXTERN int asn1D_NOTATION (OSCTXT* pctxt,
   NOTATION *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_NOTATION (OSCTXT* pctxt, 
   NOTATION* pvalue, xmlNodePtr pXmlNode);

/**************************************************************/
/*                                                            */
/*  PositiveInteger                                           */
/*                                                            */
/**************************************************************/

typedef OSUINT32 PositiveInteger;

EXTERN int asn1E_PositiveInteger (OSCTXT* pctxt,
   PositiveInteger *pvalue, ASN1TagType tagging);

EXTERN int asn1D_PositiveInteger (OSCTXT* pctxt,
   PositiveInteger *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Short                                                     */
/*                                                            */
/**************************************************************/

typedef OSINT16 Short;

EXTERN int asn1E_Short (OSCTXT* pctxt,
   Short *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Short (OSCTXT* pctxt,
   Short *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  UnsignedByte                                              */
/*                                                            */
/**************************************************************/

typedef OSUINT8 UnsignedByte;

EXTERN int asn1E_UnsignedByte (OSCTXT* pctxt,
   UnsignedByte *pvalue, ASN1TagType tagging);

EXTERN int asn1D_UnsignedByte (OSCTXT* pctxt,
   UnsignedByte *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  UnsignedInt                                               */
/*                                                            */
/**************************************************************/

typedef OSUINT32 UnsignedInt;

EXTERN int asn1E_UnsignedInt (OSCTXT* pctxt,
   UnsignedInt *pvalue, ASN1TagType tagging);

EXTERN int asn1D_UnsignedInt (OSCTXT* pctxt,
   UnsignedInt *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  UnsignedLong                                              */
/*                                                            */
/**************************************************************/

typedef OSUINT64 UnsignedLong;

EXTERN int asn1E_UnsignedLong (OSCTXT* pctxt,
   UnsignedLong *pvalue, ASN1TagType tagging);

EXTERN int asn1D_UnsignedLong (OSCTXT* pctxt,
   UnsignedLong *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  UnsignedShort                                             */
/*                                                            */
/**************************************************************/

typedef OSUINT16 UnsignedShort;

EXTERN int asn1E_UnsignedShort (OSCTXT* pctxt,
   UnsignedShort *pvalue, ASN1TagType tagging);

EXTERN int asn1D_UnsignedShort (OSCTXT* pctxt,
   UnsignedShort *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  XMLStringWithNoWhitespace                                 */
/*                                                            */
/**************************************************************/

typedef ASN1UTF8String XMLStringWithNoWhitespace;

EXTERN int asn1E_XMLStringWithNoWhitespace (OSCTXT* pctxt,
   XMLStringWithNoWhitespace *pvalue, ASN1TagType tagging);

EXTERN int asn1D_XMLStringWithNoWhitespace (OSCTXT* pctxt,
   XMLStringWithNoWhitespace *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  DateOnly                                                  */
/*                                                            */
/**************************************************************/

typedef DATE_TIME DateOnly;

EXTERN int asn1E_DateOnly (OSCTXT* pctxt,
   DateOnly *pvalue, ASN1TagType tagging);

EXTERN int asn1D_DateOnly (OSCTXT* pctxt,
   DateOnly *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Day                                                       */
/*                                                            */
/**************************************************************/

typedef DATE_TIME Day;

EXTERN int asn1E_Day (OSCTXT* pctxt,
   Day *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Day (OSCTXT* pctxt,
   Day *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Month                                                     */
/*                                                            */
/**************************************************************/

typedef DATE_TIME Month;

EXTERN int asn1E_Month (OSCTXT* pctxt,
   Month *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Month (OSCTXT* pctxt,
   Month *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  MonthDay                                                  */
/*                                                            */
/**************************************************************/

typedef DATE_TIME MonthDay;

EXTERN int asn1E_MonthDay (OSCTXT* pctxt,
   MonthDay *pvalue, ASN1TagType tagging);

EXTERN int asn1D_MonthDay (OSCTXT* pctxt,
   MonthDay *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  Year                                                      */
/*                                                            */
/**************************************************************/

typedef DATE_TIME Year;

EXTERN int asn1E_Year (OSCTXT* pctxt,
   Year *pvalue, ASN1TagType tagging);

EXTERN int asn1D_Year (OSCTXT* pctxt,
   Year *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  YearMonth                                                 */
/*                                                            */
/**************************************************************/

typedef DATE_TIME YearMonth;

EXTERN int asn1E_YearMonth (OSCTXT* pctxt,
   YearMonth *pvalue, ASN1TagType tagging);

EXTERN int asn1D_YearMonth (OSCTXT* pctxt,
   YearMonth *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  TimeOnly                                                  */
/*                                                            */
/**************************************************************/

typedef DATE_TIME TimeOnly;

EXTERN int asn1E_TimeOnly (OSCTXT* pctxt,
   TimeOnly *pvalue, ASN1TagType tagging);

EXTERN int asn1D_TimeOnly (OSCTXT* pctxt,
   TimeOnly *pvalue, ASN1TagType tagging, int length);

/**************************************************************/
/*                                                            */
/*  _SeqOfString                                              */
/*                                                            */
/**************************************************************/

typedef struct EXTERN _SeqOfString {
   OSUINT32 n;
   String *elem;
} _SeqOfString;

EXTERN int asn1E__SeqOfString (OSCTXT* pctxt,
   _SeqOfString *pvalue, ASN1TagType tagging);

EXTERN int asn1D__SeqOfString (OSCTXT* pctxt,
   _SeqOfString *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest__SeqOfString (OSCTXT* pctxt, 
   _SeqOfString* pvalue, xmlNodePtr pXmlNode);

/**************************************************************/
/*                                                            */
/*  AnyType                                                   */
/*                                                            */
/**************************************************************/

typedef struct EXTERN AnyType {
   _SeqOfString embed_values;
   _SeqOfString attr;
   _SeqOfString elem_list;
} AnyType;

EXTERN int asn1E_AnyType (OSCTXT* pctxt,
   AnyType *pvalue, ASN1TagType tagging);

EXTERN int asn1D_AnyType (OSCTXT* pctxt,
   AnyType *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_AnyType (OSCTXT* pctxt, AnyType* pvalue, xmlNodePtr pXmlNode);

/**************************************************************/
/*                                                            */
/*  ENTITIES                                                  */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ENTITIES {
   OSUINT32 n;
   ENTITY *elem;
} ENTITIES;

EXTERN int asn1E_ENTITIES (OSCTXT* pctxt,
   ENTITIES *pvalue, ASN1TagType tagging);

EXTERN int asn1D_ENTITIES (OSCTXT* pctxt,
   ENTITIES *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_ENTITIES (OSCTXT* pctxt, 
   ENTITIES* pvalue, xmlNodePtr pXmlNode);

/**************************************************************/
/*                                                            */
/*  IDREFS                                                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN IDREFS {
   OSUINT32 n;
   IDREF *elem;
} IDREFS;

EXTERN int asn1E_IDREFS (OSCTXT* pctxt,
   IDREFS *pvalue, ASN1TagType tagging);

EXTERN int asn1D_IDREFS (OSCTXT* pctxt,
   IDREFS *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_IDREFS (OSCTXT* pctxt, IDREFS* pvalue, xmlNodePtr pXmlNode);

/**************************************************************/
/*                                                            */
/*  NMTOKENS                                                  */
/*                                                            */
/**************************************************************/

typedef struct EXTERN NMTOKENS {
   OSUINT32 n;
   NMTOKEN *elem;
} NMTOKENS;

EXTERN int asn1E_NMTOKENS (OSCTXT* pctxt,
   NMTOKENS *pvalue, ASN1TagType tagging);

EXTERN int asn1D_NMTOKENS (OSCTXT* pctxt,
   NMTOKENS *pvalue, ASN1TagType tagging, int length);

EXTERN void asn1DOMTest_NMTOKENS (OSCTXT* pctxt, 
   NMTOKENS* pvalue, xmlNodePtr pXmlNode);

#ifdef __cplusplus
}
#endif

#endif
